### ISSUE TITLE
ASSERT running stac-a2: core/translate.c:931 false

### ISSUE THREAD

**Issue by rkgithubs** [DynamoRIO/dynamorio#3610] opened 2019-05-13 23:29 UTC
I'm running debug binary for a HPC app known as STAC-A2 simulation. After running DR for a while 
tracing crashes with the following crash error. 
<Invalid opcode encountered>
<Application /root/min_run_scripts/stac-a2 (131039).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/translate.c:931 false

application is run as following: 
/root/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64/drrun -debug -loglevel 2 -- /bin/bash run_stac_xyz.sh

detailed crash info pasted from the debug information. There were bunch of other commands before it which ran successfully.

<-- execve ./stac-a2 -->
<Starting application /root/min_run_scripts/stac-a2 (131039)>
<Initial options = -loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/root/DynamoRIO-x86_64-Linux-7.90.18019-0/lib64/debug/libdynamorio.so' 0x00007f10a6594580
>
<(1+x) Handling our fault in a TRY at 0x00007f10a67ddd7c>
<spurious rep/repne prefix @0x00007f10a6351f96 (f2 41 ff e3): >
<Invalid opcode encountered>
<Application /root/min_run_scripts/stac-a2 (131039).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/translate.c:931 false
(Error occurred @8293 frags)
version 7.90.18019, custom build
-loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0x00007f10863e4b40 0x00007f10a662f00e
0x00007f10863e4d90 0x00007f10a674568d
0x00007f10863e4e90 0x00007f10a674721c
0x00007f10863e5920 0x00007f10a674779a
0x00007f10863e5960 0x00007f10a67203ae
0x00007f10863e59c0 0x00007f10a681452f
0x00007f10863e5ec0 0x00007f10a6819c1e
0x00007f10863e61d0 0x00007f10a681cd1e
0x00007f10863e6370 0x00007f10a67dd89d
0x00007fff8d9e97c0 0x000000000064ee73>
stac-a2 ret val: 255

I ran three different tests under STAC-A2 simulation (one throughput, two latency)- they all failed with following: 
<Application /root/min_run_scripts/stac-a2 (131039).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/translate.c:931 false
; 
ret val: 255

from monitoring 'top' it seems application never got to the part where stac binary executes . Typically this application would spawn multiple concurrent threads (#cpucount). 
references to STAC-A2 https://ieeexplore.ieee.org/document/7016374

**Comment by AssadHashmi** [comment] 2019-05-14 10:20
Please attach log files for the failing run.
They should be in the `logs/` subdirectory of the DynamoRIO install or build directory.

**Comment by rkgithubs** [comment] 2019-05-14 17:17
there was no log file for this PID which caused the crash. <Starting application /root/min_run_scripts/stac-a2 (131039)>. I'll do another run and double-check.

**Comment by rkgithubs** [comment] 2019-05-14 19:56
I've rerun the test. There is no log directory for this PID 
[stac.loglevel3.log](https://github.com/DynamoRIO/dynamorio/files/3179574/stac.loglevel3.log)

**Comment by rkgithubs** [comment] 2019-05-14 20:06
I see the same issue coming up while running java application. For this one there is a log generated for corresponding PID (attached below)
[java.0.139682.txt](https://github.com/DynamoRIO/dynamorio/files/3179611/java.0.139682.txt)

 /root/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64/drrun -debug -loglevel 2 -- /root/jdk1.9-b160/bin/java -jar /root/IcyRocks-Java-Kernel-V1.0.2.jar 
<log dir=/root/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64/../logs/java.139682.00000000>
<Starting application /root/jdk1.9-b160/bin/java (139682)>
<Initial options = -no_dynamic_options -loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/root/DynamoRIO-x86_64-Linux-7.90.18019-0/lib64/debug/libdynamorio.so' 0x00007f1e221bc580
>
<(1+x) Handling our fault in a TRY at 0x00007f1e22405d7c>
<spurious rep/repne prefix @0x00007f1e21f79f96 (f2 41 ff e3): >
<Invalid opcode encountered>
<Application /root/jdk1.9-b160/bin/java (139682).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/translate.c:931 false
(Error occurred @18897 frags)
version 7.90.18019, custom build
-no_dynamic_options -loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0x00007f1e022a0b40 0x00007f1e2225700e
0x00007f1e022a0d90 0x00007f1e2236d68d
0x00007f1e022a0e90 0x00007f1e2236f21c
0x00007f1e022a1920 0x00007f1e2236f79a
0x00007f1e022a1960 0x00007f1e223483ae
0x00007f1e022a19c0 0x00007f1e2243c52f
0x00007f1e022a1ec0 0x00007f1e22441c1e
0x00007f1e022a21d0 0x00007f1e22444e38
0x00007f1e022a2370 0x00007f1e2240589d
0x00007f1e013251c0 0x49656e696c65746e>

**Comment by AssadHashmi** [comment] 2019-05-15 10:53
This has the same decode error as #3586 
```
spurious rep/repne prefix @0x00007f1e21f79f96 (f2 41 ff e3)
```
The `stac.loglevel3.log` file also has:
```
curiosity: rex.w on OPSZ_6_irex10_short4!
```
Have you built the binaries from source or are they pre-built downloads?

**Comment by derekbruening** [comment] 2019-05-15 14:40
The "spurious rep/repne prefix" is not fatal and can be ignored: it's #1978.  (If someone has time to submit a PR to suppress it that would be appreciated; long-term MPX support (#3581) will remove it).

The fatal issue here is:
```
<Invalid opcode encountered>
```

Please identify the opcode.  The most likely candidate is AVX-512 (#1312).  It may be that all of these recently-filed issues are from the same AVX-512 instructions being hit and are all duplicates.  But a general binary would not e expected to have AVX-512 instructions in it yet.

**Comment by derekbruening** [comment] 2019-05-15 14:42
The opcode is printed at loglevel 1 as you can see here (or just tweak your DR build to print to stderr if that's easier): https://github.com/DynamoRIO/dynamorio/blob/master/core/arch/x86/decode.c#L1

**Comment by rkgithubs** [comment] 2019-05-16 16:39
yes, stac-a2 has AVX-512 instructions. 
crash due profiling java application (s) on aarch64 #3586 is not due to AVX-512 instructions since they .jar file has no AVX-512 instructions.

**Comment by derekbruening** [comment] 2019-05-16 18:07
Closing as a duplicate of #1312.

**Closed by derekbruening** 2019-05-16 18:07 UTC
Labels: Bug-Assert, Status-NeedInfo

**Comment by rkgithubs** [comment] 2019-05-16 19:43
I just ran stac-a2 binary built for previous (broadwell) uarch which had no avx512 support. 
DR still crashes on invalid opcode line. Is there a debug step to know which opcode is it failing on. I don't think this is an avx512 instruction, we are running the binary successfully on broadwell (predecessor to skylake which had no avx512)

<Starting application /root/rahul/min_run_scripts/stac-a2 (164210)>
<Initial options = -loglevel 3 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/root/rahul/DynamoRIO-x86_64-Linux-7.90.18019-0/lib64/debug/libdynamorio.so' 0x00007f66060d4580
>
<curiosity: rex.w on OPSZ_6_irex10_short4!>
<(1+x) Handling our fault in a TRY at 0x00007f660631dd7c>
<spurious rep/repne prefix @0x00007f6605e91f96 (f2 41 ff e3): >
<Invalid opcode encountered>
<Application /root/rahul/min_run_scripts/stac-a2 (164210).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/translate.c:931 false
(Error occurred @9379 frags)
version 7.90.18019, custom build

**Comment by AssadHashmi** [comment] 2019-05-17 11:30
> Is there a debug step to know which opcode is it failing on.

I think the quickest way to do this is to run with `-debug -loglevel 1` and look for the following message:
```
Reached image entry point 0x00000000004001e4
SYSLOG_WARNING: Application /path/to/binary (9739).  Application exception at PC 0x00000000004001e4.
Signal 4 delivered to application as default action.
Callstack:
```

Dissassemble the binary with objdump and look for the faulting PC address (`4001e4` in the example above) to find the failing instruction.

Make sure that the line:
```
Signal 4 delivered to application as default action.
```
appears as above because that is the SIGILL which Linux generates in the event of an invalid opcode.

**Comment by derekbruening** [comment] 2019-05-17 16:43
No need to disassemble the binary: the invalid encoding bytes are right there in the thread logfile.  @rkgithubs, I already explicitly pointed this out in multiple places and even pointed at the DR code that does the printing so you can have it print to stderr if you want: https://github.com/DynamoRIO/dynamorio/issues/3610#issuecomment-492684583,
https://github.com/DynamoRIO/dynamorio/issues/3586#issuecomment-492680267.

**Comment by derekbruening** [comment] 2019-05-17 16:44
Or use `-log_to_stderr -loglevel 1`

**Comment by rkgithubs** [comment] 2019-05-22 23:04
I tracked down the invalid opcode in thread log file. logfile attached 
[log.0.190197.txt](https://github.com/DynamoRIO/dynamorio/files/3209627/log.0.190197.txt)


SYSLOG_WARNING: Invalid opcode encountered
Error decoding 0x000000000259eb28 == 0x62 0xf2 0xfd 0x48 0x19 0xe 
Error decoding 0x000000000259ec43 == 0x62 0xf1 0x7c 0x48 0x28 0xc1 
Error decoding 0x000000000259ec43 == 0x62 0xf1 0x7c 0x48 0x28 0xc1 
Error decoding 0x000000000259ec43 == 0x62 0xf1 0x7c 0x48 0x28 0xc1 
ERROR: recreate_app : looking for 0x0000000040274ee3 in frag @ 0x0000000040274ed4 (tag 0x000000000259ec43)
TAG  0x0000000000000000
 +0    L4 @0x00007fdc615d2930  e9 3e cf 00 a1       jmp    $0x000000000259ec43
END 0x0000000000000000

SYSLOG_ERROR: Application /root/rahul/min_run_scripts/stac-a2 (190197).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/translate.c:931 false
(Error occurred @9394 frags)
version 7.90.18019, custom build
-loglevel 1 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0x00007fdc61591b40 0x00007fdc817dc00e

**Comment by derekbruening** [comment] 2019-05-23 01:10
Those are evex bytes so that is AVX-512.
