### ISSUE TITLE
App crash on Ryzen/Win10

### ISSUE THREAD

**Issue by kmar** [DynamoRIO/dynamorio#4011] opened 2020-01-11 08:28 UTC
Due to missing support for AMD's monitorx and mwaitx, used by ntdll when running on recent AMD chips, dr reports an illegal instruction.
see https://github.com/DynamoRIO/drmemory/issues/2233

**Comment by kmar** [comment] 2020-01-11 08:42
PR here https://github.com/DynamoRIO/dynamorio/pull/4012

**Comment by derekbruening** [comment] 2020-01-13 05:16
Turns out #3577 already covers these two opcodes so let's mark this as a duplicate of #3577.

**Closed by derekbruening** 2020-01-13 05:16 UTC
