### ISSUE TITLE
Enable more compiler warnings in CI workflows

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#6060] opened 2023-05-18 04:18 UTC
Xref #6058 where we fixed an obvious bug where a variable was being moved to itself: `x = std::move(x)`. Our CI failed to catch this, but @ksco reported that the LicheePi4A (RISC-V SBC) compiler complained about it. We should enable this check in our workflows too.

**Comment by ksco** [comment] 2023-05-18 04:20
Also #6059, this one exists for a long time.

**Comment by derekbruening** [comment] 2023-05-18 17:06
The issue is that the `-Wall -Werror` we use for core DR compilation gets lost in the drcachesim CMake code.  @lihasgupta is looking into addressing this for #6040, PR #6041 -- maybe one or the other should be closed as a duplicate.

**Closed** 2023-05-24 14:40 UTC
Labels: Status-Duplicate
