### ISSUE TITLE
client can't handle lib's exceptions

### ISSUE THREAD

**Issue by 0x140ce** [DynamoRIO/dynamorio#2857] opened 2018-03-01 12:12 UTC
Hello，I use triton‘s static lib in client to achieve symbolic execution.
If symbol execution failed,triton will throw exceptions which client can't handle.
Using triton‘s static lib whithout dr is no problem,I think this is the client‘s problem to deal with the C + + exception.
What can i do to solve this issue?

**Comment by toshipiazza** [comment] 2018-03-01 12:37
Is this on Windows? I believe https://github.com/DynamoRIO/dynamorio/issues/1717 was solved for Linux clients but remains open on Windows clients.

**Comment by 0x140ce** [comment] 2018-03-02 02:17
Yes,the environment is win7.Is there any way to remedy this problem.?

**Comment by derekbruening** [comment] 2018-03-02 03:19
It sounds like this is a duplicate of #1717.  Closing this issue.  Help is wanted on providing Windows client C++ exception support if you would like to contribute to #1717.

**Closed by derekbruening** 2018-03-02 03:19 UTC
