### ISSUE TITLE
div sample failed on aarch64 machine(11.1.0)

### ISSUE THREAD

**Issue by Bri1987** [DynamoRIO/dynamorio#7162] opened 2024-12-20 13:53 UTC
**Describe the bug**
I use released version 11.1.0 on AArch64 machine, and when I try to use libdiv.so in sample, it failed and aborted.
My libc version is "ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35", I don't know if it is vital. Because when I try to use libdiv.so on another aarch64 machine which has libc version 2.28, it ran successful. (but maybe system version reason , I'm not sure)

**To Reproduce**
I copy the log here.
```
root@iZwz9h6ma9e0okfsky1r2cZ:/usr/local/software/DynamoRIO-AArch64-Linux-11.0.0/bin64# ./drrun -c ../samples/bin64/libdiv.so -- ls
<Application /usr/bin/ls (3063871).  DynamoRIO Sample Client 'div' internal crash at PC 0x00000000710a91b4.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGSEGV at pc 0x00000000710a91b4 in thread 3063871
Base: 0x0000000071000000
Registers:	eflags=0x0000000080001000
version 11.0.0, custom build
-no_dynamic_options -client_lib '/usr/local/software/DynamoRIO-AArch64-Linux-11.0.0/bin64/../samples/bin64/libdiv.so;0;' -client_lib64 '/usr/local/software/DynamoRIO-AArch64-Linux-11.0.0/bin64/../samples/bin64/libdiv.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject 
0x0000fffd5cb8bc00 0x000000007103f564
0x0000fffd5cb8bc40 0x000000007103f850
0x0000fffd5cb8bcb0 0x00000000711d079c
0x0000fffd5cb8bd70 0x000000007103e44c
0x0000fffd5cb8bf30 0x0000ffffa0b3eeb0
0x0000ffffd76060f0 0x0000ffffa0b3eeb0
0x0000ffffd7606140 0x0000ffffa0b43314
0x0000ffffd7606180 0x0000ffffa0b3f310
0x0000ffffd76064a0 0x0000ffffa0b40cb8
0x0000ffffd7606510 0x0000ffffa0b3fc4c>
```

Please also answer these questions:
 - What happens when you run without any client?
I think sample program all should be ran with -c ?
```
root@iZwz9h6ma9e0okfsky1r2cZ:/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64# drrun  ../samples/bin64/libdiv.so -- ls
Segmentation fault (core dumped)
```
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
also run fail:
```
root@iZwz9h6ma9e0okfsky1r2cZ:/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64# drrun -debug -c ../samples/bin64/libdiv.so -- ls
<Starting application /usr/bin/ls (3063934)>
<Initial options = -no_dynamic_options -client_lib '/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64/../samples/bin64/libdiv.so;0;' -client_lib64 '/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64/../samples/bin64/libdiv.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64/../samples/bin64/libdiv.so' 0x0000ffff79cc2da0
add-symbol-file '/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/lib64/debug/libdynamorio.so' 0x000000007101c2f8
add-symbol-file '/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/ext/lib64/debug/libdrmgr.so' 0x0000ffff79d01470
add-symbol-file '/lib/aarch64-linux-gnu/libc.so.6' 0x0000ffffbdb68040
add-symbol-file '/usr/lib/ld-linux-aarch64.so.1' 0x0000ffffbdb03c40
>
<(1+x) Handling our fault in a TRY at 0x0000000071446f34>
<Application /usr/bin/ls (3063934) DynamoRIO usage error : insert_parameter_preparation: bad argument type>
<Usage error: insert_parameter_preparation: bad argument type (/home/runner/work/dynamorio/dynamorio/core/arch/mangle_shared.c, line 494)
version 11.1.0, custom build
-no_dynamic_options -client_lib '/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64/../samples/bin64/libdiv.so;0;' -client_lib64 '/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64/../samples/bin64/libdiv.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject 
0x0000fffd79d5d010 0x00000000710ca2e8
0x0000fffd79d5d1b0 0x00000000714286d8
0x0000fffd79d5d220 0x000000007142a2c8
0x0000fffd79d5d360 0x00000000711f32ac
0x0000fffd79d5d440 0x00000000711f37f8
0x0000fffd79d5d600 0x0000ffff79cc2f74
0x0000fffd79d5d730 0x0000ffff79d02504
0x0000fffd79d5d770 0x0000ffff79d02a68
0x0000fffd79d5d7f0 0x0000ffff79d03428
0x0000fffd79d5d8f0 0x00000000711e9688
0x0000fffd79d5ea40 0x000000007140a080
0x0000fffd79d5ead0 0x000000007140eabc
0x0000fffd79d5eb70 0x0000000071412f78
0x0000fffd79d5ed90 0x00000000710b1514
0x0000fffd79d5ef40 0x0000ffffbdd24eb0
/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/lib64/debug/libdynamorio.so=0x0000000071000000
/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64/../samples/bin64/libdiv.so=0x0000ffff79cc2000
/lib/aarch64-linux-gnu/libc.so.6=0x0000ffffbdb41000
/usr/lib/ld-linux-aarch64.so.1=0x0000ffffbdb02000
/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/ext/lib64/debug/libdrmgr.so=0x0000ffff79cfd000>
```

**Expected behavior**
ran successful when libc version is 2.28.
```
[bri1987@node06 bin64]$ ./drrun -c ../samples/bin64/libdiv.so -- ls
drconfig	drdeploy  drinject	  drloader	  drnudgeunix	     drrun	  libdrconfiglib.a    load_syms64.txt
drconfig.debug	drdisas   drinject.debug  drloader.debug  drnudgeunix.debug  drrun.debug  libdrfrontendlib.a  nudgeunix
Instrumentation results:
  saw 1344 div instructions
  of which 367 were powers of 2
```

**Screenshots or Pasted Text**
I copy all logs, so I think it is no need.

**Versions**
 - What version of DynamoRIO are you using?
11.1.0
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
no
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
failed system version :
```
root@iZwz9h6ma9e0okfsky1r2cZ:/usr/local/software/DynamoRIO-AArch64-Linux-11.1.0/bin64# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
successful system version :
```
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"
ANSI_COLOR="0;31"
```
- Is your application 32-bit or 64-bit?
64-bit

**Comment by abhinav92003** [comment] 2024-12-20 16:49
Thanks for the bug report. Seeing a sample client crash on the latest release is indeed disturbing and we'd like to root-cause and fix this.

>  Because when I try to use libdiv.so on another aarch64 machine which has libc version 2.28, it ran successful.

We have seen issues that occur on only newer glibc versions. In fact #7120 fixed one such issue seen on glibc 2.39-4, and that's what prompted the 11.1.0 release.

I see you're already using the version 11.1.0, and I would have expected it to run fine with GLIBC 2.35 as it's been around for a while. 

> successful system version :

The shared details don't include the Linux kernel version. Is that different than the "failed system version"?

> I think sample program all should be ran with -c ?

To run without a client, simply use "drrun -- ls". Does it crash also?

>> What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
> also run fail:

It would help to see a symbolized crash callstack. Try the commands listed at "Example Gdb Session" at https://dynamorio.org/page_debugging.html.

**Comment by abhinav92003** [comment] 2024-12-20 20:31
I was able to reproduce this issue on an Ubuntu 22.04.5 LTS VM with GLIBC 2.35-0ubuntu3.8.

Plain DR works fine. Sample clients like libbbcount.so, libbbsize.so, and libopcode_count.so work fine too, so does drmemtrace and most drcachesim online tests.

Looks like this is limited to libdiv.so.

**Comment by abhinav92003** [comment] 2024-12-20 20:49
I see the crash happens when the div client attempts to instrument the following instruction:

```
udiv   %w2 %w6 -> %w5
```

at

https://github.com/DynamoRIO/dynamorio/blob/73b1df12b3484032045e07923668a7c834511469/api/samples/div.c#L140

dr_insert_clean_call documents the requirement that the args should be pointer-sized regs, but in the above instruction it is a 4-byte w reg, hence the assert crash.

https://github.com/DynamoRIO/dynamorio/blob/73b1df12b3484032045e07923668a7c834511469/core/lib/dr_ir_utils.h#L423

This just needs a reg_to_pointer_sized call. I'll send the fix.

**Closed** 2024-12-21 02:07 UTC
Labels: OpSys-AArch64, Bug-ToolCrash
