### ISSUE TITLE
DynamoRIO won't build due warnings

### ISSUE THREAD

**Issue by baptistapedro** [DynamoRIO/dynamorio#3806] opened 2019-08-30 10:01 UTC
I dont know why you guys implemented this but seems that DynamoRIO won't build successfully if there is any warning.

confirm here: https://dpaste.de/Zi2y/raw

**Comment by hgreving2304** [comment] 2019-08-30 13:26
In extreme cases, a warning may be disabled if it is not possible to fix
otherwise, but this is rare.

**Comment by derekbruening** [comment] 2019-08-30 18:40
This is an issue asking us to disable warnings-as-errors in general?  That is not good programming practice: warnings are there for a reason.  If this is an issue about particular warnings you are hitting, probably you're not using a supported toolchain.  See https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build.  On Windows, VS2013 is the supported compiler.  VS2015 #2166 and VS2017 #2924 are known to hit some warnings and there is some ongoing work to add support for those, but these days not many core developers work on Windows and the work is taking some time.  Closing as a duplicate of one of the two VS2015/17 issues linked previously.

**Closed by derekbruening** 2019-08-30 18:40 UTC
Labels: Status-Duplicate
