### ISSUE TITLE
SPEC jbb'15 [jdk8] core dump/fails to run 

### ISSUE THREAD

**Issue by rkgithubs** [DynamoRIO/dynamorio#3876] opened 2019-10-07 22:33 UTC
I'm trying to run SPEC jbb'15 using jdk1.8 version which is not built with avx512 flag option. We are able to run small java micros using this jdk version and collect DR traces .
SPECjbb'15 fails to run via drrun with the following error.
Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/signal.c:531 !YMM_ENABLED() || ALIGNED(pend_unit_size, AVX_ALIGNMENT)

```
@ /home/nwpa02/tools/DynamoRIO-x86_64-Linux-7.90.17998-0/bin64/drrun -- /bin/bash /workloads/SPECjbb2015/goMLQ.sh
ext 0x00007f11ca94f080)

DR stack is 0x00007f11ca98e000-0x00007f11ca99c000 (passed in 0x0000000000000000)
thread_locks=0x00007f11ca8e0058 size=8
thread_stats=0x00007f11ca8e0068 size=6840
thread_kstats=0x00007f11ca8e1b28 size=3192
threads_started
SYSLOG_ERROR: Application /bin/bash (6352).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/signal.c:531 !YMM_ENABLED() || ALIGNED(pend_unit_size, AVX_ALIGNMENT)
(Error occurred @0 frags)
version 7.90.17998, custom build
-no_dynamic_options -loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct
0x00007fff3ea5d520 0x00007f11eec9d539
0x00007fff3ea5d770 0x00007f11eee7bd3c
0x00007fff3ea5d820 0x00007f11eee65952
0x00007fff3ea5d8d0 0x00007f11eec16cb9
0x00007fff3ea5d920 0x00007f11eec14226
0x00007fff3ea5e150 0x00007f11eee99c62
0x00007fff3ea5edb0 0x00007f11eee4a8cf
DynamoRIO call stack:

Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/signal.c:531 !YMM_ENABLED() || ALIGNED(pend_unit_size, AVX_ALIGNMENT)
```
I tried to run turn debug loglevel 2 ON though DR crashes immediately. Inside the *logs* directory  there is one file (attached here) 
[log.0.2492.txt](https://github.com/DynamoRIO/dynamorio/files/3699895/log.0.2492.txt)

```
/home/nwpa02/tools/DynamoRIO-x86_64-Linux-7.90.17998-0/bin64/drrun -debug -loglevel 2 -- /bin/bash /workloads/SPECjbb2015/goMLQ.sh
<log dir=/home/nwpa02/tools/DynamoRIO-x86_64-Linux-7.90.17998-0/bin64/../logs/bash.2492.00000000>
<Starting application /bin/bash (2492)>
<Initial options = -no_dynamic_options -loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Application /bin/bash (2492).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/signal.c:531 !YMM_ENABLED() || ALIGNED(pend_unit_size, AVX_ALIGNMENT)
(Error occurred @0 frags)
```

**Comment by derekbruening** [comment] 2019-10-07 22:58
Looks like a duplicate of #3380 which is fixed.  Please try a more recent build.

**Closed by derekbruening** 2019-10-07 22:58 UTC

**Comment by rkgithubs** [comment] 2019-10-08 17:35
#3380 fixed the above mentioned issues with AVX_ALIGNMENT. jbb'15 run now fails at the following error: 
```
/home/nwpa02/tools/DynamoRIO-x86_64-Linux-7.91.18173-0/bin64/drrun -debug -loglevel 2 -- /home/nwpa02/workloads/JVM/jdk1.8.0_201/bin/java -jar /workloads/SPECjbb2015/jbb102/specjbb2015.jar -m COMPOSITE

SYSLOG_ERROR: Application /home/nwpa02/workloads/JVM/jdk1.8.0_201/bin/java (3682).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/dispatch.c:757 wherewasi == DR_WHERE_FCACHE || wherewasi == DR_WHERE_TRAMPOLINE || wherewasi == DR_WHERE_APP || (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH)
(Error occurred @96716 frags)
```
attached 
[java.0.3682.txt](https://github.com/DynamoRIO/dynamorio/files/3703792/java.0.3682.txt)

**Comment by hgreving2304** [comment] 2019-10-08 17:52
xref #3175
