### ISSUE TITLE
<Application /bin/ls (10314). Cannot correctly handle a received signal.>

### ISSUE THREAD

**Issue by vanhauser-thc** [DynamoRIO/dynamorio#2841] opened 2018-02-20 18:44 UTC
I followed the wiki and installed the necessary tools do by debian, cloned the repository, cmake in build directory, make, make install ...

drrun --ls => works
drrun -t drcov -- ls => works
but running any library fails with:

/src/dynamorio/build/bin64/drrun -c /src/dynamorio/build/api/bin/libinstrcalls.so -- /bin/ls
<Application /bin/ls (10314). Cannot correctly handle a received signal.>

the .so is x64 too:
/src/dynamorio/build/api/bin/libinstrcalls.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a958040b304adb74d7c1c7ae6143908034c16934, not stripped

what is going wrong? is there a bug in the current repository state?

**Comment by derekbruening** [comment] 2018-02-20 19:14
Maybe #2751?

**Comment by vanhauser-thc** [comment] 2018-02-20 23:52
I do not have a crash, but if it is because of some libc or other issue it could well be.

I tried the precompiled 7.0-RC1 release and have a slightly different outcome:

/src/DynamoRIO-Linux-7.0.0-RC1 # bin64/drrun -c samples/bin64/libinstrcalls.so -- ls
/src/DynamoRIO-Linux-7.0.0-RC1 #

it generates no output whatsoever, it does not matter which -c .so I am loading and which binary I am executing.

It also does not make a difference when I use as a target a static compiled binary, or if it was compiled with gcc or clang, or if I use the musl-libc.
Maybe its libc that it loaded when drrun is run. My libc version is 2.26. Kernel is 4.14.0

I tried on a different machine (but also Debian and same update level) and have the same result when either compiling dynamorio or using 7.0-RC1 

Not sure it helps, attached is an strace.
[strace.txt](https://github.com/DynamoRIO/dynamorio/files/1742353/strace.txt)

**Comment by derekbruening** [comment] 2018-02-21 00:02
> I do not have a crash

It's an unhandled signal, likely SIGSEGV == crash.
Please run with -debug: is it the same sig=11 message as #2751?

**Comment by vanhauser-thc** [comment] 2018-02-21 00:33
debug on my compiled dynamorio:
 /src/dynamorio/build # bin64/drrun -debug -c api/bin/libinstrcalls.so -- /bin/ls
ERROR: cannot find required file /prg/tmp/dynamorio/build/bin64/../lib64/debug/libdynamorio.so
Use -root to specify a proper DynamoRIO root directory.

How would I compile the debug version of the library?

For 7.0-RC1:

/src/DynamoRIO-Linux-7.0.0-RC1 # bin64/drrun -debug -c samples/bin64/libinstrcalls.so -- ls
<Starting application /bin/ls (28440)>
<ERROR: master_signal_handler with no siginfo (i#26?): tid=28440, sig=11>

**Comment by vanhauser-thc** [comment] 2018-02-21 08:24
Valgrind says:
valgrind --trace-children=yes -v -- bin64/drrun -c api/bin/libinstrcalls.so -- /bin/ls
...
==832== 1 errors in context 1 of 1:
==832== Invalid read of size 8
==832==    at 0x4E9CEB7: ??? (in /lib/x86_64-linux-gnu/libc-2.26.so)
==832==  Address 0x28 is not stack'd, malloc'd or (recently) free'd
==832== 

if I add -debug to drrun valgrind crashes on reading libdynamorio.so ;)

**Comment by derekbruening** [comment] 2018-03-04 19:09
Marking as duplicate of #2751

**Closed by derekbruening** 2018-03-04 19:09 UTC
Labels: Status-Duplicate
