### ISSUE TITLE
Arch Linux - build/dynamorio/bin64/drconfig has   too-recent import: GLOBAL DEFAULT UND stat@GLIBC_2.33 (3)

### ISSUE THREAD

**Issue by mikaellenz** [DynamoRIO/dynamorio#5192] opened 2021-11-04 15:15 UTC
Arch Linux 5.10.75-1-lts #1 SMP Wed, 20 Oct 2021 11:02:09 +0000 x86_64 GNU/Linux

CMake Error at /mnt/ramdisk/drmemory/dynamorio/core/CMake_readelf.cmake:146 (message):
  *** Error: /mnt/ramdisk/drmemory/build/dynamorio/bin64/drconfig has
  too-recent import: GLOBAL DEFAULT UND stat@GLIBC_2.33 (3)
  
make[2]: *** [dynamorio/tools/CMakeFiles/drconfig.dir/build.make:102: dynamorio/bin64/drconfig] Error 1
make[2]: *** Deleting file 'dynamorio/bin64/drconfig'
make[1]: *** [CMakeFiles/Makefile2:1491: dynamorio/tools/CMakeFiles/drconfig.dir/all] Error 2

make[2]: *** No rule to make target 'dynamorio/ext/lib64/release/libdrcontainers.a', needed by 'bin64/release/libdrmemorylib.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:945: CMakeFiles/drmemorylib.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

[cmake_configure.log](https://github.com/DynamoRIO/dynamorio/files/7475867/cmake_configure.log)

Please tell me if additional info required.

**Comment by derekbruening** [comment] 2021-11-04 23:29
Duplicate of #5130.

**Closed by derekbruening** 2021-11-04 23:29 UTC
