### ISSUE TITLE
attaching to running process not yet implemented 

### ISSUE THREAD

**Issue by rkgithubs** [DynamoRIO/dynamorio#3597] opened 2019-05-08 21:41 UTC
for large applications is there currently a way to attach to running PID on-the-fly. I tried using -attach option with drrun which failed with following message. 
./drrun -attach 16601
ERROR: attaching to running processes is not yet implemented

Is there a workaround or alternative which allows for tracing a particular steady-state portion of the application. I can try the -trace_after_instrs option but i need to be sure that instruction count reported by 'perf stat' is consistent with the way dynamoRIO counts retired instructions otherwise we run the risk of tracing wrong part of the application execution. Please advise on a good approach.

**Comment by derekbruening** [comment] 2019-05-08 21:52
Duplicate of #38, #725
Xref PR #3328 which adds attach but is not yet merged.

Internally-triggered attach (dr_app_start()) is supported today.

**Closed by derekbruening** 2019-05-08 21:52 UTC

**Comment by derekbruening** [comment] 2019-05-08 21:53
#3107 is the feature request for tracing boundary marking in the app

**Comment by derekbruening** [comment] 2019-05-08 21:54
Internally-triggered is how most current users have been doing this.  #3328 should be easy to finish up however.
