### ISSUE TITLE
APPCRASH during runtime using a HelloWorld example

### ISSUE THREAD

**Issue by SkyBulk** [DynamoRIO/dynamorio#3904] opened 2019-10-19 16:36 UTC
I am trying to get hands-on about dynamorio, but dynamorio crashes during runtime from the app.

it was compiled with `cl from_file.c` , but however when I tried to use against dynamorio the app crashes with the following error. 

![issue](https://user-images.githubusercontent.com/43649816/67148297-817e6200-f25b-11e9-95f5-563c7c370baf.png)

the source code from the example code is below. 

[from_file.c.zip](https://github.com/DynamoRIO/dynamorio/files/3746912/from_file.c.zip)

sample working without dynamorio 

```sh
C:\Users\aroni>C:\Users\aroni\Documents\from_file.c\from_file.exe C:\Users\aroni\Documents\from_file.c\from_file.exe
CASE_13 [nread>16] common
```
sample with dynamorio appcrah

```sh
C:\Users\aroni>C:\Users\aroni\Documents\DynamoRIO-Windows-7.1.0-1\bin32\drrun.exe -debug -t drcov -- C:\Users\aroni\Documents\from_file.c\from_file.exe C:\Users\aroni\Documents\from_file.c\from_file.exe
```

machine builds 

```
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.18362 N/A Build 18362
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1600 Mhz
```

**Comment by derekbruening** [comment] 2019-10-19 17:09
Looks like a duplicate of #3391.  Is this Win10 1809 (don't have a build#-to-release# mapping)?  That's the version # that counts.  Run winver or sthg to see the version.  Recent DR releases put the version in the diagnostic message but 7.1 is too old.

Try the latest cronbuild: it has #3391 fixed.  https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build

**Closed by derekbruening** 2019-10-19 17:09 UTC
