### ISSUE TITLE
DynamoRIO and Chrome Sandbox

### ISSUE THREAD

**Issue by newgre** [DynamoRIO/dynamorio#1645] opened 2015-03-26 12:46 UTC
When running Chrome, it spawns several child processes (e.g. one or more renderer processes). These child processes are locked down in terms of ACL restrictions and privilege levels. Sepcifically, the renderer processes run on the "untrusted" integrity level.
However, when starting Chrome with DynamoRIO, i.e.,

drrun -- $Chrome.exe

those renderer processes instead run on "low" integrity level. 
This seems to indicate, that DynamoRIO somehow interferes with the way Chrome enforces restrictions on child processes.

My OS is Win7 x64 using Chrome 41.0.2272.101 m and DynamoRIO 5.1.0-RC1

**Comment by derekbruening** [comment] 2015-03-26 17:40
I can't reproduce this on a Chromium chrome.exe that I built:

```
% ~/dr/releases/DynamoRIO-Windows-5.1.0-RC1/bin32/drrun -stderr_mask 15 -- out/Release/chrome.exe --user-data-dir='c:\cygwin\tmp\chrome' http://web.mit.edu
<Starting application Z:\derek\chromium\src\out\Release\chrome.exe (1788)>
<Stopping application Z:\derek\chromium\src\out\Release\chrome.exe (1788)>
```

ProcessExplorer with the Integrity column shows the gpu process as Low and the renderer as Untrusted:

```
Process	PID	CPU	Private Bytes	Working Set	Description	Company Name	Path	Command Line	Image Type	DEP	ASLR	Integrity
  drrun.exe	6248		4,424 K	6,456 K	DynamoRIO configure-and-run command-line utility	DynamoRIO developers	D:\derek\dr\releases\DynamoRIO-Windows-5.1.0-RC1\bin32\drrun.exe	D:\derek\dr\releases\DynamoRIO-Windows-5.1.0-RC1\bin32\drrun.exe -stderr_mask 15 -- out/Release/chrome.exe --user-data-dir=c:\cygwin\tmp\chrome http://web.mit.edu	32-bit	DEP (permanent)	ASLR	Medium
   chrome.exe	1788	0.01	104,336 K	181,972 K	Chromium	The Chromium Authors	Z:\derek\chromium\src\out\Release\chrome.exe	out/Release/chrome.exe --user-data-dir=c:\cygwin\tmp\chrome http://web.mit.edu	32-bit	DEP (permanent)	ASLR	Medium
    chrome.exe	6308		86,008 K	113,148 K	Chromium	The Chromium Authors	Z:\derek\chromium\src\out\Release\chrome.exe	"Z:\derek\chromium\src\out\Release\chrome.exe" --type=gpu-process --channel="1788.0.1228679648\2141394928" --user-data-dir="c:\cygwin\tmp\chrome" --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,18,41 --gpu-vendor-id=0x0000 --gpu-device-id=0x0000 --gpu-driver-vendor --gpu-driver-version --user-data-dir="c:\cygwin\tmp\chrome" --ignored=" --type=renderer " /prefetch:822062411	32-bit	DEP (permanent)	ASLR	Low
    chrome.exe	1120		63,064 K	121,144 K	Chromium	The Chromium Authors	Z:\derek\chromium\src\out\Release\chrome.exe	"Z:\derek\chromium\src\out\Release\chrome.exe" --type=renderer --enable-deferred-image-decoding --lang=en-US --force-fieldtrials=*InfiniteCache/No/*Prerender/PrerenderMulti/ --user-data-dir="c:\cygwin\tmp\chrome" --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --device-scale-factor=1 --font-cache-shared-mem-suffix=1788 --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --channel="1788.2.720978632\616097405" /prefetch:673131151	32-bit	DEP (permanent)	ASLR	Untrusted

Process: chrome.exe Pid: 6308

Path	Base	Size	Name	Description	Company Name	Version	Image Type	Mapping
Z:\derek\chromium\src\out\Release\chrome.exe	0x1130000	0xAB000	chrome.exe	Chromium	The Chromium Authors	43.0.2318.0	32-bit	Image
...
D:\derek\dr\releases\DynamoRIO-Windows-5.1.0-RC1\lib32\release\dynamorio.dll	0x6DBB0000	0x14F000	dynamorio.dll	DynamoRIO core library	DynamoRIO developers	5.1.0.0	32-bit	Image
```

Which exactly matches native:

```
% out/Release/chrome.exe --user-data-dir='c:\cygwin\tmp\chrome' http://web.mit.edu
```

```
Process	PID	CPU	Private Bytes	Working Set	Description	Company Name	Path	Command Line	Image Type	DEP	ASLR	Integrity
  chrome.exe	6584	< 0.01	29,704 K	92,392 K	Chromium	The Chromium Authors	Z:\derek\chromium\src\out\Release\chrome.exe	Z:\derek\chromium\src\out\Release\chrome.exe --user-data-dir=c:\cygwin\tmp\chrome http://web.mit.edu	32-bit	DEP (permanent)	ASLR	Medium
   chrome.exe	4228		57,100 K	76,664 K	Chromium	The Chromium Authors	Z:\derek\chromium\src\out\Release\chrome.exe	"Z:\derek\chromium\src\out\Release\chrome.exe" --type=gpu-process --channel="6584.0.298491710\946272018" --user-data-dir="c:\cygwin\tmp\chrome" --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,18,41 --gpu-vendor-id=0x0000 --gpu-device-id=0x0000 --gpu-driver-vendor --gpu-driver-version --user-data-dir="c:\cygwin\tmp\chrome" --ignored=" --type=renderer " /prefetch:822062411	32-bit	DEP (permanent)	ASLR	Low
   chrome.exe	2060		22,908 K	78,776 K	Chromium	The Chromium Authors	Z:\derek\chromium\src\out\Release\chrome.exe	"Z:\derek\chromium\src\out\Release\chrome.exe" --type=renderer --enable-deferred-image-decoding --lang=en-US --force-fieldtrials=*InfiniteCache/No/*Prerender/PrerenderMulti/ --user-data-dir="c:\cygwin\tmp\chrome" --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --device-scale-factor=1 --font-cache-shared-mem-suffix=6584 --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --channel="6584.1.87761094\255515577" /prefetch:673131151	32-bit	DEP (permanent)	ASLR	Untrusted
```

**Comment by derekbruening** [comment] 2015-03-26 17:56
I can reproduce running an official Chrome build version 41.0.2272.101 m: the gpu is Low and the renderer is also Low.  Hmm.

**Comment by derekbruening** [comment] 2015-03-27 17:21
Actually I can't reproduce.  What I'm seeing is the problem of ProcessExplorer caching the integrity level.  Right-clicking on Properties and looking at Security I see "Mandatory Label\Untrusted Mandatory Level  Integrity" (vs the same thing but s/Untrusted/Low/ for gpu process).  If I restart ProcExp it then shows Untrusted for the rendered under DynamoRIO.

newgre, what evidence do you have that the renderer was not in Untrusted?  Was it just the ProcExp caching problem?

**Comment by derekbruening** [comment] 2015-03-27 17:31
From offline communication: the original evidence was indeed the ProcessExplorer column, likely from a ProcessExplorer instance that was running the whole time and so hit the caching problem.

Closing.

**Closed by derekbruening** 2015-03-27 17:31 UTC
Labels: Bug-AppFail, OpSys-Windows, Status-Invalid, Transparency, Type-Bug
