### ISSUE TITLE
[AArch64] Release-build hang in tool.drcacheoff.max-global 

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#5366] opened 2022-02-17 16:07 UTC
tool.drcacheoff.max-global failed on AArch64 in a CI run on PR #5364. I tried running it 100 times locally and it worked fine. Looking at logs, they seem to be cut short. Maybe it crashed?
Logs: http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/1334/console

**Comment by derekbruening** [comment] 2022-02-17 16:41
This is a timeout (90s is the limit) and so likely a hang:
```
66/66 Test #212: code_api|tool.drcacheoff.max-global .............................***Failed   90.03 sec
```

This might be the plain-DR hang I found in https://github.com/DynamoRIO/dynamorio/issues/4928#issuecomment-1043154222 which was the cause of dr$sim -offline hangs in my runs.  With PR #5367 -offline does not hang (ran 20K in a row) so I would be willing to bet that this is fixed by that PR.

**Closed** 2022-02-17 17:09 UTC
Labels: Component-Tests, OpSys-AArch64
