### ISSUE TITLE
win64 burst_replaceall non-det failure

### ISSUE THREAD

**Issue by xdje42** [DynamoRIO/dynamorio#6523] opened 2023-12-21 00:04 UTC
This bug is akin to #6423. In this case it's either non-deterministic output in the
`code_api|tool.drcacheoff.burst_replaceall` testcase or the expected output needs updating.
This is in the vs2019-64 test run of patch #6522.
https://github.com/DynamoRIO/dynamorio/actions/runs/7280553778/job/19842932375?pr=6522

Actual vs Expected attached as files.
[burst_replaceall.actual.txt](https://github.com/DynamoRIO/dynamorio/files/13733611/burst_replaceall.actual.txt)
[burst_replaceall.expected.txt](https://github.com/DynamoRIO/dynamorio/files/13733612/burst_replaceall.expected.txt)

**Comment by derekbruening** [comment] 2023-12-21 00:42
Duplicate of #5412

**Closed by derekbruening** 2023-12-21 00:42 UTC
