### ISSUE TITLE
 Sample Client 'memval' internal crash at PC 0x00007f0a28c681d3.  Please report this at http://dynamorio.org/issues.  Program aborted.

### ISSUE THREAD

**Issue by atharvabhanage12** [DynamoRIO/dynamorio#6375] opened 2023-10-18 08:51 UTC
**Describe the bug**
 Sample Client 'memval' internal crash at PC 0x00007f0a28c681d3.  Please report this at http://dynamorio.org/issues.  Program aborted.

drrun -root /dr_dynamorio/drio/DynamoRIO-Linux-10.0.19613  -c /dr_dynamorio/drio/DynamoRIO-Linux-10.0.19613/samples/build_ath_track/bin/libmemval_simple.so -- ./myprogram_test1
Data file /dr_dynamorio/drio/DynamoRIO-Linux-10.0.19613/samples/build_ath_track/bin/memval.myprogram_test1.1003557.0000.log created
<Application /home/athbha01/dr_dynamorio/working_my_space/myprogram_test1 (1003557).  DynamoRIO Sample Client 'memval' internal crash at PC 0x00007fee0c4681d3.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGSEGV at pc 0x00007fee0c4681d3 in thread 1003557
Base: 0x00007fee0ca00000
Registers:eax=0x0000000000000000 ebx=0x00007febc8ae1c60 ecx=0x0000000000000000 edx=0x00000000fbad248c
	esi=0x00000000fbad0000 edi=0x00007ffdabb74e90 esp=0x00007ffdabb74e88 ebp=0x0000000000000000
	r8 =0x00007fee0c5ed0c0 r9 =0x00007fedc8a06012 r10=0x00007fee0cbde000 r11=0x0000000000000246
	r12=0x00007ffdabb74e90 r13=0x00007fee0c5f2a50 r14=0x0000000000000000 r15=0x00007febc8ae1c60
	eflags=0x0000000000010246
version 10.0.19613, custom build
-no_dynamic_options -client_lib '/dr_dynamorio/drio/DynamoRIO-Linux-10.0.19613/samples/build_ath_track/bin/libmemval_simple.so;0;' -client_lib64 '/dr_dynamorio/drio/DynamoRIO-Linux-10.0.19613/samples/build_ath_track/bin/libmemval_simple.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -
0x00007febc8a92080 0x0000000000000000>

this is error its crashing.  this also happened for memtrace_simple

**Comment by derekbruening** [comment] 2023-10-18 21:35
There is not enough information here.  Looks like you have deleted the rest of the bug template: why?  As you can imagine, no one will be able to reproduce this without access to "myprogram_test1", and possibly without access to your exact platform and environment.  Please follow standard bug reporting steps for any system: minimize the reproducer; describe whether it works with other applications; etc.  Without further information (please paste in the rest of the template which you have deleted) we will have to close this as not actionable.

**Comment by atharvabhanage12** [comment] 2023-10-19 06:43
This is all the output error is.  the code in myprogram_test1 is essentially just a load and store  that's all

running on x86, rest of the samples works ut these related to mem are crashing.

**Comment by derekbruening** [comment] 2023-10-19 21:18
Closing due to failure to provide basic information in the template https://github.com/DynamoRIO/dynamorio/issues/new?assignees=&labels=&template=bug_report.md&title= such as the precise platform OS distro, what happens with debug build, etc., plus questions in https://github.com/DynamoRIO/dynamorio/issues/6375#issuecomment-1769358666 like what happens with other applications and providing a reproducer ("just a load and store" is not sufficient: is that pure assembly (even then it probably has a syscall to exit) or C and thus has thousands of other instructions from ld and libc??  Clearly "just a load and store" work on most platforms as the automated tests of the memval client on simple apps like hello,world (which of course contain many loads and stores) work fine.). If enough info is provided, including the precise "load and store" that trigger this and probably also requires a callstack in the debugger of the crash point as this is likely not reproducible on other platforms, we can re-open.

**Closed by derekbruening** 2023-10-19 21:18 UTC
Labels: Status-Invalid, Status-NeedInfo
