### ISSUE TITLE
APP CRASH: x64 Windows & TLS under drcov

### ISSUE THREAD

**Issue by expend20** [DynamoRIO/dynamorio#4136] opened 2020-02-25 11:52 UTC
Hi! 
I've got a simple app which tries to extract thumbnail from image. The problem is it causes a crash being run under DR, and runs fine without DR. When I run it under DR, the post-mortem debugger attaches to the process and I'm able to see the cause of it, which seems related to TLS structure.

```
(2798.3964): Access violation - code c0000005 (!!! second chance !!!)
CompPkgSup!CacheCodecExtensions+0x33:
00007ffd`bcd07f2f 428b0401        mov     eax,dword ptr [rcx+r8] ds:00000000`00000004=????????
0:000> k
 # Child-SP          RetAddr           Call Site
00 000000b7`f28fc5d0 00007ffd`bcd0b602 CompPkgSup!CacheCodecExtensions+0x33
01 000000b7`f28fc690 00007ffd`bcd0c424 CompPkgSup!GetMediaComponentPackageInfoInternal+0x4fe
02 000000b7`f28fc7b0 00007ffd`bd486309 CompPkgSup!GetMediaComponentPackageInfo+0x64
03 000000b7`f28fc800 00007ffd`bd48362f MFPlat!EnumPackagedMFTs+0x141
04 000000b7`f28fc9f0 00007ffd`bdff1df6 MFPlat!MFTEnumEx+0x25f
05 000000b7`f28fcb30 00007ffd`bdff274c MSRAWImage!CreateWICComponent+0x2ee
06 000000b7`f28fccb0 00007ffd`c7df70b5 MSRAWImage!CWICRAWDecoderClassFactory::CreateInstance+0x4c
07 000000b7`f28fcd00 00007ffd`c7db4840 combase!CServerContextActivator::CreateInstance+0x1d5 [onecore\com\combase\objact\actvator.cxx @ 881] 
08 000000b7`f28fce80 00007ffd`c7df6c3c combase!ActivationPropertiesIn::DelegateCreateInstance+0x90 [onecore\com\combase\actprops\actprops.cxx @ 1983] 
09 000000b7`f28fcf10 00007ffd`c7e54228 combase!CApartmentActivator::CreateInstance+0x9c [onecore\com\combase\objact\actvator.cxx @ 2189] 
0a 000000b7`f28fcfc0 00007ffd`c7e58890 combase!CProcessActivator::CCICallback+0x58 [onecore\com\combase\objact\actvator.cxx @ 1640] 
0b 000000b7`f28fd010 00007ffd`c7e50971 combase!CProcessActivator::AttemptActivation+0x40 [onecore\com\combase\objact\actvator.cxx @ 1527] 
0c 000000b7`f28fd060 00007ffd`c7e54730 combase!CProcessActivator::ActivateByContext+0x91 [onecore\com\combase\objact\actvator.cxx @ 1371] 
0d 000000b7`f28fd0f0 00007ffd`c7db4840 combase!CProcessActivator::CreateInstance+0x80 [onecore\com\combase\objact\actvator.cxx @ 1271] 
0e 000000b7`f28fd140 00007ffd`c7e01cff combase!ActivationPropertiesIn::DelegateCreateInstance+0x90 [onecore\com\combase\actprops\actprops.cxx @ 1983] 
0f 000000b7`f28fd1d0 00007ffd`c7db4840 combase!CClientContextActivator::CreateInstance+0x17f [onecore\com\combase\objact\actvator.cxx @ 570] 
10 000000b7`f28fd480 00007ffd`c7de6047 combase!ActivationPropertiesIn::DelegateCreateInstance+0x90 [onecore\com\combase\actprops\actprops.cxx @ 1983] 
11 000000b7`f28fd510 00007ffd`c7de4b09 combase!ICoCreateInstanceEx+0x917 [onecore\com\combase\objact\objact.cxx @ 2028] 
12 000000b7`f28fe400 00007ffd`c7de494c combase!CComActivator::DoCreateInstance+0x169 [onecore\com\combase\objact\immact.hxx @ 386] 
13 (Inline Function) --------`-------- combase!CoCreateInstanceEx+0xd1 [onecore\com\combase\objact\actapi.cxx @ 177] 
14 000000b7`f28fe560 00007ffd`b9d46702 combase!CoCreateInstance+0x10c [onecore\com\combase\objact\actapi.cxx @ 121] 
15 000000b7`f28fe600 00007ffd`b9d1fa9c windowscodecs!CCodecInfo::CreateInstance+0xe2
16 000000b7`f28fe640 00007ffd`b9d21b6e windowscodecs!CCodecFactory::HrArbitrateDecoderList+0x5e4
17 000000b7`f28fe790 00007ffd`b9d47cb2 windowscodecs!CCodecFactory::HrCreateDecoderFromStreamInternalNew+0x30e
18 000000b7`f28fe870 00007ffd`a78a76f4 windowscodecs!CCodecFactory::CreateDecoderFromStream+0x72
19 000000b7`f28fe8d0 00007ffd`c56f65fe PhotoMetadataHandler!CPhotoThumbnailProvider::Initialize+0x104
1a 000000b7`f28fe960 00007ffd`c56f5e21 windows_storage!InitializeFileHandlerWithStream+0x16e
1b 000000b7`f28fea20 00007ffd`c5678e74 windows_storage!CFileSysItemString::HandlerCreateInstance+0x2e9
1c 000000b7`f28feb10 00007ffd`c56b1c3c windows_storage!CFileSysItemString::LoadHandler+0x1f4
1d 000000b7`f28fec60 00007ffd`c567a456 windows_storage!CFSFolder::s_GetThumbnailExtractor+0x18c
1e 000000b7`f28feff0 00007ffd`c574e4b2 windows_storage!CFSFolder::_BindHandler+0x5c6
1f 000000b7`f28ff380 00007ffd`c56c20a9 windows_storage!CFSFolder::GetThumbnailHandler+0x62
20 000000b7`f28ff400 00007ffd`c566e71d windows_storage!_CreateThumbnailHandler+0xa9
*** WARNING: Unable to verify checksum for z:\s\bb\ms\ms-thumbnail\vs-thumb-get\open\x64\Release\open.exe
21 000000b7`f28ff4c0 00007ff6`ec2d108f windows_storage!CShellItem::BindToHandler+0x69d
22 000000b7`f28ff820 00007ff6`ec2d120d open!fuzz+0x8f [z:\s\bb\ms\ms-thumbnail\vs-thumb-get\open\open\Source.cpp @ 36] 
23 000000b7`f28ff890 00007ff6`ec2d1474 open!main+0xfd [z:\s\bb\ms\ms-thumbnail\vs-thumb-get\open\open\Source.cpp @ 87] 
24 (Inline Function) --------`-------- open!invoke_main+0x22 [d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
25 000000b7`f28ffaf0 00007ffd`c9706fd4 open!__scrt_common_main_seh+0x10c [d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
26 000000b7`f28ffb30 00007ffd`c9ca2c41 KERNEL32!BaseThreadInitThunk+0x14
27 000000b7`f28ffb60 00000000`00000000 ntdll!RtlUserThreadStart+0x21
0:000> ub
CompPkgSup!CacheCodecExtensions+0xc:
00007ffd`bcd07f08 4157            push    r15
00007ffd`bcd07f0a 488bec          mov     rbp,rsp
00007ffd`bcd07f0d 4881ec80000000  sub     rsp,80h
00007ffd`bcd07f14 65488b042558000000 mov   rax,qword ptr gs:[58h]
00007ffd`bcd07f1d 4c8be1          mov     r12,rcx
00007ffd`bcd07f20 8b1572630200    mov     edx,dword ptr [CompPkgSup!tls_index (00007ffd`bcd2e298)]
00007ffd`bcd07f26 b904000000      mov     ecx,4
00007ffd`bcd07f2b 4c8b04d0        mov     r8,qword ptr [rax+rdx*8]
```

**To Reproduce**
1. The binary takes path to the file as command line parameter. You should run it like this:
```
open.exe <path to attached bmp without extension> .bmp
```
* [open.exe](https://minio.tw1st.link/permanent/public/open.exe) 
* [bmp](https://minio.tw1st.link/permanent/public/bmp)
The program just prints (via OutputDebugString) "-" in this sample.
2. Running the same command under DR leads to aforementioned APP CRASH.
```
drrun.exe -t drcov -- open.exe bmp .bmp
```

Please also answer these questions:
 - What happens when you run without any client?
   - "-" is printed to dbgview.exe
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
   - I actually didn't find the way how I can feed "-debug" to drcov

**Versions**
 - What version of DynamoRIO are you using?
   - 7.91.18301.2 
 - Does the latest build from
https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build solve the problem?
    - nope
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
    - Version 10.0.18363.657
- Is your application 32-bit or 64-bit?
    - 64 bit

**Additional context**

Here is full [crashdump](https://minio.tw1st.link/permanent/public/full-dumpfile.dmp)

**Comment by derekbruening** [comment] 2020-02-25 16:01
> > What happens when you run without any client?
> "-" is printed to dbgview.exe

?  Is the crash there, or not?  "Without any client" means no drcov: just `drrun -- open.exe bmp .bmp`

> > What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
> I actually didn't find the way how I can feed "-debug" to drcov

Like it says, it is a flag to *drrun*, not drcov.  `drrun -debug -- open.exe bmp .bmp`

**Comment by expend20** [comment] 2020-03-03 22:32
Oh, sorry I've completely missed your answer, thanks for reply!

>? Is the crash there, or not? "Without any client" means no drcov: just drrun -- open.exe bmp .bmp

I misunderstood it. Just running `drrun -- open.exe bmp .bmp` gives no crash, probably the problem is in coverage client then?

>drrun -debug -- open.exe bmp .bmp

Running `drrun.exe -debug -t drcov -- open.exe bmp .bmp` gives following output before crash:

```
c:\temp\dynamorio>z:\s\tools\dr791\bin64\drrun.exe -debug -t drcov -- open.exe c:\temp\dynamorio\bmp .bmp
<Starting application c:\temp\dynamorio\open.exe (22668)>
<Running on newer-than-this-build "Microsoft Windows 10-2004 x64">
<Early threads found>
<Initial options = -no_dynamic_options -client_lib 'z:\s\tools\dr791\tools\lib64\release\drcov.dll;0;' -code_api -probe_api -stack_size 56K -nop_initial_bblock -max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<curiosity: rex.w on OPSZ_6_irex10_short4!>
<Application changing protections of system memory at least once (0x00007fffbf4d4000-0x00007fffbf4d8000)>
```

**Comment by expend20** [comment] 2020-03-16 13:32
Hi @derekbruening!

I've found other pretty simple and informative sample to demonstrate problems related to TLS. [Here is](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/multimedia/wic/wicanimatedgif) small sample from Microsoft. If you compile it either x64 or x86 and run under `drcov` it will lead to a crash. 

Here is stack call for x86 version

```
(4448.1260): Access violation - code c0000005 (!!! second chance !!!)
eax=08fee054 ebx=00000006 ecx=8c000400 edx=00000000 esi=00000000 edi=00770000
eip=773edd26 esp=004fa640 ebp=004fa6c8 iopl=0         nv up ei pl zr na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210246
ntdll!LdrpHandleTlsData+0x2df:
773edd26 ff71fc          push    dword ptr [ecx-4]    ds:002b:8c0003fc=????????
0:000> k
 # ChildEBP RetAddr  
00 004fa6c8 773edd80 ntdll!LdrpHandleTlsData+0x2df
01 004fa6e0 773f4204 ntdll!LdrpDoPostSnapWork+0x4b
02 004fa790 773f66dd ntdll!LdrpSnapModule+0x3d4
03 004fa7c8 774034c5 ntdll!LdrpMapAndSnapDependency+0x21d
04 004fa7f0 774197c9 ntdll!LdrpMapDllWithSectionHandle+0x16b
05 004fa850 7740ba60 ntdll!LdrpMapDllNtFileName+0x11f
06 004fa980 773f4e40 ntdll!LdrpMapDllFullPath+0xb8
07 004fa9d0 773f504b ntdll!LdrpProcessWork+0x112
08 004faa18 77404dec ntdll!LdrpLoadDllInternal+0x18f
09 004fab58 77404d13 ntdll!LdrpLoadDll+0x7e
0a 004fabd8 752915df ntdll!LdrLoadDll+0x93
0b 004fac1c 74c98752 KERNELBASE!LoadLibraryExW+0x14f
```

Could you please look at it? 

Thanks

**Comment by derekbruening** [comment] 2020-03-16 19:15
Thank you for the reproducer.  Note that since most of us do not work on Windows regularly I do not know when someone will have time to spend investigating.  If you would like to take a stab at debugging that might be the most timely way forward.

**Comment by expend20** [comment] 2020-03-25 01:20
I've tried to look at it. No much info but so far it looks like this.

When crash happens, code is accessing TEB->ThreadLocalStoragePointer + 0xf*8. Here is how it should be (without DR):

```
0:000> dq @rax L12
0000017a`a9b37f40  0000017a`a1fefff0 0000017a`a203fff0
0000017a`a9b37f50  0000017a`a20a5ff0 0000017a`a20e5ff0
0000017a`a9b37f60  0000017a`a21adff0 0000017a`a21c9ff0
0000017a`a9b37f70  0000017a`a21e7ff0 0000017a`a271aff0
0000017a`a9b37f80  0000017a`a28aeff0 0000017a`a2971ff0
0000017a`a9b37f90  0000017a`a8a4bff0 0000017a`a8c23ff0
0000017a`a9b37fa0  0000017a`a95a2ff0 0000017a`a960cff0
0000017a`a9b37fb0  0000017a`a97a2ff0 0000017a`a98daff0
0000017a`a9b37fc0  0000017a`a9b33ff0 0000017a`a9b79ff0 <=== last qword is accessed
```

An here is how it looks like under DR:

```
000001ae`4bb41f80  000001ae`4b20cff0 000001ae`4b266ff0
000001ae`4bb41f90  000001ae`4b2c0ff0 000001ae`4b306ff0
000001ae`4bb41fa0  000001ae`4b3ceff0 000001ae`4b3f2ff0
000001ae`4bb41fb0  000001ae`4b404ff0 000001ae`4b9abff0
000001ae`4bb41fc0  000001ae`4bb3fff0 000001ae`4bc02ff0
000001ae`4bb41fd0  000001ae`d2d92ff0 000001ae`d2f1aff0
000001ae`4bb41fe0  000001ae`d389aff0 000001ae`d3906ff0
000001ae`4bb41ff0  00000000`00000000 00000000`00000000 <=== last 2 qwords are zero
```

So, it looks very similar except last two elements.

I've searched through DR code for looking for `STATIC_TLS_TIB_OFFSET` and `dcontext->priv_static_tls` and found quite a few places where it's used. But no clue what may went wrong.

**Comment by expend20** [comment] 2020-03-25 12:24
I've found in longs:

```
app static_tls=0x0000021e4f322fc0, priv static_tls=0x0000000000000000
```

At the crash time it looks like this:

```
2:011> dq 0x0000021e4f322fc0
0000021e`4f322fc0  0000021e`4f31eff0 0000021e`4f372ff0
0000021e`4f322fd0  0000021e`4f3d0ff0 0000021e`4f412ff0
0000021e`4f322fe0  0000021e`4f4deff0 0000021e`4f4f2ff0
0000021e`4f322ff0  0000021e`4f514ff0 0000021e`4fac1ff0
0000021e`4f323000  ????????`???????? ????????`????????
0000021e`4f323010  ????????`???????? ????????`????????
0000021e`4f323020  ????????`???????? ????????`????????
0000021e`4f323030  ????????`???????? ????????`????????
```

And for the failing code it is:

```
0000021e`4fc57f80  0000021e`4f31eff0 0000021e`4f372ff0
0000021e`4fc57f90  0000021e`4f3d0ff0 0000021e`4f412ff0
0000021e`4fc57fa0  0000021e`4f4deff0 0000021e`4f4f2ff0
0000021e`4fc57fb0  0000021e`4f514ff0 0000021e`4fac1ff0
0000021e`4fc57fc0  0000021e`4fc55ff0 0000021e`4fd18ff0
0000021e`4fc57fd0  0000021e`d6fe9ff0 0000021e`d716fff0
0000021e`4fc57fe0  0000021e`d7aecff0 0000021e`d7b56ff0
0000021e`4fc57ff0  00000000`00000000 00000000`00000000
0000021e`4fc58000  ????????`???????? ????????`????????
```

The first 8 quad words are the same, but then data mentioned in logs is over. I've also noticed that if I raise log level more than 2 DR is crashing before the origin bug happens.

**Comment by expend20** [comment] 2020-03-25 23:08
@derekbruening could you give any pointers, pls?

**Comment by derekbruening** [comment] 2020-03-28 21:08
Is the problem that the *app* static TLS is messed up and so the app crashes?  I.e., it's not that drcov uses some system lib who needs static TLS and it's the *private* static TLS that is messed up?

The first callstack in https://github.com/DynamoRIO/dynamorio/issues/4136#issue-570516358 seems to be an app callstack, except the current PC is in an app dll, which should not happen under DR: it should be in the code cache (unless it's later, in the app's exception handler, but it looks like a first-chance there?).  So I'm confused about that callstack.  Not sure how this post-mortem debugger is invoked.

The second callstack is a dynamic load of a new library: is that also in the app?  I assume that's not client or private since the load should be redirected.  But again the PC looks like it's in the library.  How are you obtaining these callstacks?

If drcov's imports do not need static TLS, you could try reverting  9293e7ae7709ee78fe520722dbe062b8680126d6 (may need to also revert 064f8a720a549b640dcfddc5a5eb7b036d373e32) to see if the crash goes away, to see whether the problem is in DR's swapping of TEB->ThreadLocalStoragePointer.

**Comment by expend20** [comment] 2020-03-28 21:32
Thanks! I'll read your message several times, cause I don't get everything you said :) For now I can only answer on this:

> How are you obtaining these callstacks?

I just have post-mortem debugger, it pops up when crash happens. I don't know actually why I can see valid stack call instead of DR's code cache. On some crashes I can see valid stack calls, on others (I mean totally different crashes to this topic) I can't. So, when WinDBG is popped I can see that data at TEB->ThreadLocalStoragePointer is different to what it should be without DR, that's why it's crashed. Never the less, data at TEB->ThreadLocalStoragePointer is mostly valid, the difference is only last 0x10 bytes.

**Comment by derekbruening** [comment] 2020-03-28 21:38
I think reverting those commits would be a good test.

If that makes it go away, the next step would be to see whether it's a missing swap somewhere -- but if the private value is 0 the entire time you'd think it'd crash right there instead of later.  There are sanity checks that the right value is in the TEB in dispatch and other places that usually catch simple swapping bugs though.

If you know where the bad values are, maybe do a native run with a watchpoint to see who writes there, and then find that point in the DR run?

**Comment by expend20** [comment] 2020-04-13 22:51
I've tried it from another perspective. First of all I minimized the failing code to only one call to GetOpenFileName() which loads a lot of COM/OLE stuff. Just if someone want to follow along here is the full source :)

```cpp
#include <windows.h>
#include <stdio.h>

int main() {
	OPENFILENAMEA ofn = {0};
	
	char szFile[260] = {0};
	ofn.nMaxFile = sizeof(szFile);
	ofn.lpstrFilter = "All\0*.*\0";
	ofn.nFilterIndex = 1;
	ofn.lpstrFileTitle = NULL;
	ofn.nMaxFileTitle = 0;
	ofn.lpstrInitialDir = NULL;
	ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

	ofn.lStructSize = sizeof(ofn);
	ofn.lpstrFile = szFile;

	GetOpenFileNameA(&ofn);

	printf("%s\n", ofn.lpstrFile);
}
```

I'm actually not quite sure if this is the same bug as an original one, but the failing function seems to be `ntdll!LdrpHandleTlsData` which may be related issue because it uses Tls (and it's extremely easy to reproduce it):

```
 # Child-SP          RetAddr           Call Site
00 00000086`bc51a160 00007ff9`b11d529d ntdll!LdrpHandleTlsData+0x43f
01 00000086`bc51a260 00007ff9`b119cb2a ntdll!LdrpDoPostSnapWork+0x6d
02 00000086`bc51a2b0 00007ff9`b11a31d1 ntdll!LdrpSnapModule+0x49a
03 00000086`bc51a3b0 00007ff9`b11aa100 ntdll!LdrpMapAndSnapDependency+0x235
04 00000086`bc51a430 00007ff9`b11ad5b7 ntdll!LdrpMapDllWithSectionHandle+0x184
05 00000086`bc51a480 00007ff9`b11ae608 ntdll!LdrpMapDllNtFileName+0x183
06 00000086`bc51a580 00007ff9`b11ae360 ntdll!LdrpMapDllFullPath+0xe0
07 00000086`bc51a710 00007ff9`b11a2536 ntdll!LdrpProcessWork+0x74
08 00000086`bc51a770 00007ff9`b11a22a8 ntdll!LdrpLoadDllInternal+0x13e
09 00000086`bc51a7f0 00007ff9`b11a1764 ntdll!LdrpLoadDll+0xa8
0a 00000086`bc51a9a0 00007ff9`ae7d56f0 ntdll!LdrLoadDll+0xe4
0b 00000086`bc51aa90 00007ff9`b0ba4b80 KERNELBASE!LoadLibraryExW+0x170
...
```

Then I built `9293e7ae7709ee78fe520722dbe062b8680126d6~1` revision in a debug configuration and got an assertion here:

```
---------------------------
DrCov Notice: C:\Users\john\source\repos\temp0\x64\Debug\temp0.exe(20276)
---------------------------
Application C:\Users\john\source\repos\temp0\x64\Debug\temp0.exe (20276).  Internal Error: DynamoRIO debug check failure: Z:\s\git\dynamorio\core\dispatch.c:757 wherewasi == DR_WHERE_FCACHE || wherewasi == DR_WHERE_TRAMPOLINE || wherewasi == DR_WHERE_APP || (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH)
(Error occurred @222587 frags)
version 7.91.33333, custom build
-no_dynamic_options -client_lib 'z:\s\git\dynamorio\build_dbg\clients\lib64\debug\drcov.dll;0;' -code_api -probe_api -stack_size 56K -nop_initial_bblock -max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -pad_jmps_mark_no_trace 
0x000000b55edf6ee0 0x0000000000000000
z:\s\git\dynamorio\build_dbg\clients\lib64\debug\drcov.dll=0x00007ff7946e0000
z:\s\git\dynamorio\build_dbg\ext\lib64\debug/drcovlib.dll=0x00007ff7946f0000
z:\s\git\dynamorio\build_dbg\ext\lib64\debug/drx.dll=0x00007ff794700000
z:\s\git\dynamorio\build_dbg\ext\lib64\debug/drreg.dll=0x00007ff794720000
z:\s\git\dynamorio\build_dbg\ext\lib64\debug/drmgr.dll=0x00007ff794730000
---------------------------
OK   
---------------------------
```

Which is the code:

```
    ASSERT(wherewasi == DR_WHERE_FCACHE || wherewasi == DR_WHERE_TRAMPOLINE ||
           wherewasi == DR_WHERE_APP ||
           /* If the thread was waiting at check_wait_at_safe_point when getting
            * suspended, we were in dispatch (ref i#3427). We will be here after the
            * thread's context is being reset before sending it native.
            */
           (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH));
```

The same exact assertion is hit in master branch. I'm not quite understand where I can move from there :-\

**Comment by hongphipham95** [comment] 2020-05-15 04:17
I reverted the 9293e7ae7709ee78fe520722dbe062b8680126d6 commit and it works for me. But I still not find out where the missing swap happens

**Comment by hongphipham95** [comment] 2020-05-15 12:18
I debugged with the poc at https://github.com/DynamoRIO/dynamorio/issues/4136#issuecomment-613135121.

In https://github.com/DynamoRIO/dynamorio/issues/4136#issuecomment-603587710, the last qword of the TEB->ThreadLocalStoragePointer (without DR) is initialized with 0 at first. But later, `LdrpHandleTlsData()` function will add an entry to the TLS array at slot `_tls_index`. 
When we run with DR, there's something wrong with the commit 9293e7ae7709ee78fe520722dbe062b8680126d6 that prevents `LdrpHandleTlsData()` function to add the entry and causes a crash when the current thread access to the missing TLS slot.
This happens in different DLLs each run and causes a crash when the thread calls this function: https://docs.microsoft.com/en-us/cpp/cppcx/wrl/module-class?view=vs-2019#getmodule

**Comment by expend20** [comment] 2020-05-15 14:22
@hongphipham95 thanks for your participation! Could you please describe how did you revert the commit? Did you just use `git revert 9293e7a` and resolve all the conflicts manually? I've tried to checkout 9293e7a~1 and the bug was still there.

**Comment by hongphipham95** [comment] 2020-05-15 14:26
I used `git checkout 0a3c7f40d109573d5484c9fb010efda9a14b9157` . It's the parent commit. It solve the bug in my machine, you can try.

**Comment by expend20** [comment] 2020-05-15 14:50
Thanks @hongphipham95! It worked indeed, I guess I didn't notice it working because I was using debug build of the same commit.

**Comment by hongphipham95** [comment] 2020-05-15 14:57
I tried to apply the commit 9293e7ae7709ee78fe520722dbe062b8680126d6 part by part but failed to see where things go wrong.

**Comment by vbty** [comment] 2020-07-17 06:34
Hi, i meet this bug too. Wil anyone fix it?

**Comment by derekbruening** [comment] 2021-01-30 00:09
Based on http://www.nynaeve.net/Code/VistaImplicitTls.cpp and `LdrpHandleTlsData` using `NtSetInformationProcess.ProcessTlsInformation` to update the `TEB.ThreadLocalStoragePointer` array in other threads: is the kernel updating another thread while that thread is in DR mode and thus it fails to enact the update??  If that's how it operates that's not good: it makes it really hard to have private state without doing a global synch on all threads every time any one thread invokes `NtSetInformationProcess.ProcessTlsInformation`.

**Comment by derekbruening** [comment] 2021-01-30 16:58
Testing the theory, I had DR allocate a 64-entry array (even though drcov and its libs don't need any at all and leave the TEB field NULL normally) and I checked in dispatch if any entry was non-zero.

Running the POC from above, we indeed see 3 threads suddenly have non-zero entries.  Here's one appearing in thread 0:
```
d_r_dispatch: target = 0x00007ffcba9f9a0e
Fragment 182557, tag 0x00007ffcba9f9a0e, flags 0x9000630, shared, size 35:
        [COMDLG32.dll~GetFileTitleW+0x52ee,~PrintDlgW-0x1c602]
Entry into F182557(0x00007ffcba9f9a0e).0x00007ff70973ff99 (shared)
Exit from F182557(0x00007ffcba9f9a0e).0x00007ff70973ffa0 (shared)
 (target 0x00007ffcbaa2dee5 not in cache)
app static tls=0x000001b84c0cb650 priv static tls=0x000001b6485130d0

d_r_dispatch: target = 0x00007ffcbaa2dee5
Fragment 182558, tag 0x00007ffcbaa2dee5, flags 0x1000030, shared, size 89:
        [COMDLG32.dll~DllCanUnloadNow+0xa9e5,~ChooseColorA-0x8bcb]
Entry into F182558(0x00007ffcbaa2dee5).0x00007ff70973ffc8 (shared)
Exit from sourceless ibl: bb jmp*       []
 (target 0x00007ffcba41afa0 in cache but not lookup table)
app static tls=0x000001b84c0cb650 priv static tls=0x000001b6485130d0
zzz [26]=0x000001b84c0f3400
fragment_add_ibl_target added F154213(0x00007ffcba41afa0), branch 2, to indjmp_bb, on exit from 0x0000000000000000
add_ibl_target: shared BB F154213(0x00007ffcba41afa0) added
```

Thread 6 has entries appear 3 separate times:
```
logs/i4136.exe.2824.00000000/log.6.11740.html:57450:zzz [22]=0x000001b84c1702e0
<...>
logs/i4136.exe.2824.00000000/log.6.11740.html:73254:zzz [22]=0x000001b84c1702e0
logs/i4136.exe.2824.00000000/log.6.11740.html:73255:zzz [23]=0x000001b84c0b0c60
<...>
logs/i4136.exe.2824.00000000/log.6.11740.html:242696:zzz [22]=0x000001b84c1702e0
logs/i4136.exe.2824.00000000/log.6.11740.html:242697:zzz [23]=0x000001b84c0b0c60
logs/i4136.exe.2824.00000000/log.6.11740.html:242698:zzz [25]=0x000001b84c08e410
```

So is our best solution to add NtSetInformationProcess to the syscalls that DR takes action on, and for ProcessTlsInformation (all variants of it?):
+ Suspend all the other threads
+ For threads not already in app state, force a swap to app state
+ Now execute the syscall
+ Then resume all other threads

Executing a syscall as the app normally goes through a full fcache_enter and fcache_return and it feels a little scary leaving DR with the rest of the world suspended: that violates invariants on holding DR locks while in the cache.  We may need to execute the syscall from DR.  Hopefully there will be no alertable point where a callback comes in there...then we're in trouble.

**Comment by derekbruening** [comment] 2021-01-30 19:45
If the private TLS array is zero sized, as it is for drcov, we should disable the swap code and avoid the synchall.  Long-term this has some complexities: since a private library could dynamically load a new private lib that has static TLS, this can't be an init-time static decision, incurring the cost of a check and branch on every single swap.  Right now, we don't support dynamic static TLS though, so we could conceivably have a static decision: if we re-arrange some init-time orderings so that generated swap code knows whether to swap this TEB field or not.

**Comment by derekbruening** [comment] 2021-01-30 20:44
A quick synchall prototype works!  The file dialog pops up now in the POC app.
It had to do 29 synchalls in this POC app:
```
% grep -c ^ProcessTlsI `ls -1td logs/*0|head -1`/log.*
logs/i4136.exe.9812.00000000/log.0.10804.html:21
logs/i4136.exe.9812.00000000/log.1.8272.html:0
logs/i4136.exe.9812.00000000/log.10.7032.html:0
logs/i4136.exe.9812.00000000/log.11.9668.html:5
logs/i4136.exe.9812.00000000/log.12.732.html:1
logs/i4136.exe.9812.00000000/log.13.404.html:1
logs/i4136.exe.9812.00000000/log.14.984.html:0
logs/i4136.exe.9812.00000000/log.15.7592.html:0
logs/i4136.exe.9812.00000000/log.2.3876.html:0
logs/i4136.exe.9812.00000000/log.3.13280.html:0
logs/i4136.exe.9812.00000000/log.4.11572.html:0
logs/i4136.exe.9812.00000000/log.5.10392.html:0
logs/i4136.exe.9812.00000000/log.6.10000.html:1
logs/i4136.exe.9812.00000000/log.7.5476.html:0
logs/i4136.exe.9812.00000000/log.8.6000.html:0
logs/i4136.exe.9812.00000000/log.9.6252.html:0
```

There are no 'zzz' priv TLS non-zero diagnostics anymore.  Looks good.

**Closed** 2021-01-31 17:28 UTC
Labels: Bug-AppCrash, Component-DRTool, OpSys-Windows, help wanted

**Comment by derekbruening** [comment] 2021-01-31 17:35
@expend20, thank you for the small reproducer in https://github.com/DynamoRIO/dynamorio/issues/4136#issuecomment-613135121 -- that made it possible to figure out and fix the problem.

**Comment by expend20** [comment] 2021-01-31 17:44
> @expend20, thank you for the small reproducer in [#4136 (comment)](https://github.com/DynamoRIO/dynamorio/issues/4136#issuecomment-613135121) -- that made it possible to figure out and fix the problem.

Not at all, thank you for the fix!
