### ISSUE TITLE
CRASH (8.0.0-1 notepad.exe) internal crash at PC 0x6b94f94b on AMD Ryzen 5 2400G

### ISSUE THREAD

**Issue by electricworry** [DynamoRIO/dynamorio#4384] opened 2020-07-28 10:38 UTC
**Describe the bug**
I am having an issue specifically running 32-bit analysis on 64-bit Windows on and AMD Ryzen 5 2400G processor. The crash will occur for any invocation (e.g. "C:\DynamoRIO\bin32\drrun.exe notepad"). I believe something about my system (whether it's the processor or something else) is a factor in the issue as my notes below evidence.

I have already had a [brief discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dynamorio-users/D3qjdvg4Dug) on the user group.

My problem occured in a VM running Windows 10 2004 x64, but the same thing happens when I run bare-metal on Windows 10 2004 x64 which I believe eliminates the virtualisation as the issue.

When I attempt to do the same on my laptop (Dell XPS 13 9380 with Intel Core i7-8565U, and in a VM) I face no issue.

The problem is not improved by using a weekly build. I had the same problem with a weekly build (e.g. 8.0.18463).

**To Reproduce**
1. Install a pristine Windows 10 2004 x64 installation on a similar system. I don't expect anyone to have a system just like mine so I won't elaborate on that, but it has a Ryzen 5 2400G APU.
2. Extract DynamoRIO 8.0.0-1 to C:\DynamoRIO.
3. Open command prompt and CD to C:\DynamoRIO\bin32.
4. "drrun.exe notepad"
5. Immediate crash (output below)

Please also answer these questions:
 - What happens when you run without any client? My example above fits this questions I believe.
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)? Please see output below.

**Expected behavior**
I expect the program to run without crashing.

**Screenshots or Pasted Text**
The following crash was the result of invocation "drrun.exe notepad":
```
DynamoRIO Notice: C:\Windows\SysWOW64\notepad.exe(7204)
Application C:\Windows\SysWOW64\notepad.exe(7204).
DynamoRIO internal crash at PC 0x6b94f94b. Please report
this at http://dynamorio.org/issues. Program aborted.
0xc0000005 0x00000000 0x6b94f94b 0x6b94f94b 0x00000003
0x00000000
Base: 0x6b8a0000
Registers: eax=0x00000000 ebx=0x0093ede8 ecx=0x1d18cbc4 edx=0x00000000
           esi=0x1ae327ec edi=0x00000188 esp=0x0093ee08 ebp=0x0093eebc
           eflags=0x0001
version 8.0.0, build 1
-no_dynamic_options -code_api -probe_api -stack_size 56K
-max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls
-native_exec_default_list ;'' -no_native_exec_managed_code
-no_indcall2direct -no_aslr_dr
0x0093eebc 0x6b927949
0x6b9d7266 0x64000000
```

The following crash is the result of invocation: "drrun.exe -debug -- notepad":

```
DynamoRIO Notice: C:\Windows\SysWOW64\notepad.exe(8100)
Application C:\Windows\SysWOW64\notepad.exe(8100).
DynamoRIO internal crash at PC 0x6b867a0b. Please report
this at http://dynamorio.org/issues. Program aborted.
0xc0000005 0x00000000 0x6b867a0b 0x6b867a0b 0x00000003
0x00000000
Base: 0x6b550000
Registers: eax=0x00000000 ebx=0x0094e8c8 ecx=0x1d18cbc4 edx=0x00000000
           esi=0x163a9f30 edi=0x0094e978 esp=0x0094e8e8 ebp=0x0094e91c
           eflags=0x0001
version 8.0.0, build 1
-no_dynamic_options -code_api -probe_api -stack_size 56K
-max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls
-native_exec_default_list ;'' -no_native_exec_managed_code
-no_indcall2direct -no_aslr_dr
0x0094e91c 0x6b7f0359
0x0094e948 0x6b7f07e8
0x0094f4a8 0x6b7e3348
0x0094f4e8 0x6b55fce8
0x0094f51c 0x6b7c8d32
0x0094f588 0x6b7c94b8
```

**Versions**
 - What version of DynamoRIO are you using? 8.0.0-1
 - Does the latest build from
https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build solve the problem? 8.0.18463 does not solve the problem.
- What operating system version are you running on? Windows 10 Version 2004 (OS Build 19041.264)
- Is your application 32-bit or 64-bit? Application is 32-bit.

**Additional context**
None

**Comment by electricworry** [comment] 2020-07-28 12:23
I'm happy to do anything requested on this, whether it's getting more useful logs, or doing a build on my machine and attempting to debug it. I may need assistance as I'm new to the project but I'd like to help if I can.

**Comment by derekbruening** [comment] 2020-07-28 13:51
Is this the same as #4091?  Identifying the location of the crash should confirm it.

**Comment by derekbruening** [comment] 2020-07-28 14:13
> I'm happy to do anything requested on this, whether it's getting more useful logs, or doing a build on my machine and attempting to debug it. I may need assistance as I'm new to the project but I'd like to help if I can.

Thank you for offering to help.  First would be confirming the crash is inside dynamorio!switch_modes_and_call and is indeed #4091.  Then we'd close this as a dup and move discussion to that issue, where we need help from those with Ryzen processors to answer the questions in https://github.com/DynamoRIO/dynamorio/issues/4091#issuecomment-590552063

**Comment by electricworry** [comment] 2020-07-28 14:29
Thank you. Reading through the linked issue, does WinDbg (64-bit) have everything I need to test that for you? I spend most of my time on Linux so I'm a bit out of my comfort zone here.

**Comment by derekbruening** [comment] 2020-07-28 14:36
> Thank you. Reading through the linked issue, does WinDbg (64-bit) have everything I need to test that for you? I spend most of my time on Linux so I'm a bit out of my comfort zone here.

Yes.  Use debug build, run the smallest app that reproduces, attach at the popup msgbox.  See https://github.com/DynamoRIO/dynamorio/wiki/Debugging for how to load DR's symbols.  Just disassembling the PC in the message `DynamoRIO internal crash at PC 0x6b94f94b` should do it -- even without symbols, getting the disassembly around that PC should do it.

**Comment by electricworry** [comment] 2020-07-29 09:56
Ok I'm working kind of blind here, and I'm using official build 8.0.0-1.

I've run "bin32\drrun.exe -debug notepad.exe" and it's stuck on the exception dialog.

Now I've run WinDbg 64-bit, using the WOW64 scripts: "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe" -pt 1 -c "$><C:\Users\Worry\projects\dynamorio\tools\windbg-scripts\load_symsWOW64"

After attaching to the process I get:

```

Microsoft (R) Windows Debugger Version 10.0.14321.1024 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00000000`00bd0000 00000000`00c08000   C:\DynamoRIO\bin32\drrun.exe
ModLoad: 00007ff9`00470000 00007ff9`00664000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 00000000`77c80000 00000000`77e22000   ntdll.dll
ModLoad: 00007ff9`003d0000 00007ff9`00429000   C:\Windows\System32\wow64.dll
ModLoad: 00007ff8`ff3b0000 00007ff8`ff433000   C:\Windows\System32\wow64win.dll
ModLoad: 00000000`77c70000 00000000`77c7a000   C:\Windows\System32\wow64cpu.dll
ModLoad: 00000000`767f0000 00000000`768e0000   KERNEL32.dll
ModLoad: 00000000`777a0000 00000000`779b3000   KERNELBASE.dll
ModLoad: 00000000`665d0000 00000000`66609000   drconfiglib.dll
ModLoad: 00000000`66540000 00000000`665ca000   drinjectlib.dll
ModLoad: 00000000`76a00000 00000000`76a79000   ADVAPI32.dll
ModLoad: 00000000`76240000 00000000`762ff000   msvcrt.dll
ModLoad: 00000000`76c40000 00000000`76cb5000   SECHOST.dll
ModLoad: 00000000`76180000 00000000`7623a000   RPCRT4.dll
(7fc.b0c): Break instruction exception - code 80000003 (first chance)
ntdll!DbgBreakPoint:
00007ff9`0050e880 cc              int     3
Processing initial command '$><C:\Users\Worry\projects\dynamorio\tools\windbg-scripts\load_symsWOW64'
0:004> $><C:\Users\Worry\projects\dynamorio\tools\windbg-scripts\load_symsWOW64
Memory access error at ') + @$t0+5) & 0xfffff000);;$$ Check magic values to avoid executing random command w/o DynamoRIO;.if (dwo(@$t1) = b1d2ae58) {;    .if (dwo(@$t1 + 4) = ca50c356) {;        .if (dwo(@$t1 + 8) = 63000089) {;            .if (dwo(@$t1 + c) = 3fa898f0) {;                aS /c ${/v:loadpriv} .printf "%ma", @$t1 + 2c;                .block { ${loadpriv} };                ad ${/v:loadpriv};            } .else {;                .echo "DynamoRIO not detected";            };        } .else {;            .echo "DynamoRIO not detected";        };    } .else {;        .echo "DynamoRIO not detected";    };} .else {;    .echo "DynamoRIO not detected";};'
0:004> k
 # Child-SP          RetAddr           Call Site
00 00000000`0097fac8 00007ff9`0053ba5e ntdll!DbgBreakPoint
01 00000000`0097fad0 00007ff9`004bcecf ntdll!DbgUiRemoteBreakin+0x4e
02 00000000`0097fb00 00000000`00000000 ntdll!RtlUserThreadStart+0x2f
```
(Note the memory access error. Not sure if that's typical.)

Attempting to view the disassembly of the PC (which is 0x663a7a0b when running with -debug)
![image](https://user-images.githubusercontent.com/10690531/88786008-d73c4f00-d189-11ea-9a43-16d911c4ccc8.png)

**Comment by derekbruening** [comment] 2020-07-29 14:13
You want to attach to notepad.exe, not drrun.exe.  (On UNIX drrun execs the app and so disappears, but on Windows drrun sits around as a separate parent process, since execve does not exist.)

**Comment by electricworry** [comment] 2020-07-29 15:18
Sorry, knew I was doing something wrong.

Here's the disassembly for the function containing 0x663a7a0b.
```
dynamorio!switch_modes_and_call:
00000000`663a79bd 8bc4            mov     eax,esp
00000000`663a79bf 83c004          add     eax,4
00000000`663a79c2 8b4c240c        mov     ecx,dword ptr [rsp+0Ch]
00000000`663a79c6 8b542410        mov     edx,dword ptr [rsp+10h]
00000000`663a79ca 53              push    rbx
00000000`663a79cb 8b5c2418        mov     ebx,dword ptr [rsp+18h]
00000000`663a79cf ea              ???
00000000`663a79d0 d6              ???
00000000`663a79d1 793a            jns     dynamorio!load_dynamo (00000000`663a7a0d)
00000000`663a79d3 663300          xor     ax,word ptr [rax]
00000000`663a79d6 4154            push    r12
00000000`663a79d8 4155            push    r13
00000000`663a79da 4156            push    r14
00000000`663a79dc 4157            push    r15
00000000`663a79de 448bc3          mov     r8d,ebx
00000000`663a79e1 8bdc            mov     ebx,esp
00000000`663a79e3 83ec20          sub     esp,20h
00000000`663a79e6 83e4f0          and     esp,0FFFFFFF0h
00000000`663a79e9 488b00          mov     rax,qword ptr [rax]
00000000`663a79ec ffd0            call    rax
00000000`663a79ee 8be3            mov     esp,ebx
00000000`663a79f0 415f            pop     r15
00000000`663a79f2 415e            pop     r14
00000000`663a79f4 415d            pop     r13
00000000`663a79f6 415c            pop     r12
00000000`663a79f8 68087a3a66      push    offset dynamorio!switch_modes_and_call+0x4b (00000000`663a7a08)
00000000`663a79fd c744240423000000 mov     dword ptr [rsp+4],23h
00000000`663a7a05 ff2c24          jmp     fword ptr [rsp]
00000000`663a7a08 83c408          add     esp,8
00000000`663a7a0b 5b              pop     rbx
00000000`663a7a0c c3              ret
```
This would seem to indicate the same issue, would you agree?

**Comment by derekbruening** [comment] 2020-07-29 15:24
Yes, that's enough to convince me it's a duplicate.  Let's move further discussion to #4091.  Closing.

**Closed by derekbruening** 2020-07-29 15:24 UTC
