### ISSUE TITLE
Introducing segmentation fault in the latest version?

### ISSUE THREAD

**Issue by timhai88** [DynamoRIO/dynamorio#3910] opened 2019-10-26 03:24 UTC
I just debug the latest version of DynamoRIO (beb2ded8ac9e83a02fe418, Wed Oct 23 15:43:06 2019 +0100) and find that it wrongly introduces segmentation faults. 

1. I used the following command to debug a gadget program:
A:  gdb --args ./bin64/drrun -debug -loglevel 3 -- signal_SIGALARM
B:  symbol-file /path_to/build_debug/lib64/debug/libdynamorio.so
C: b handle_system_call
D: Continue ...

2. the output is listed as follows:
----------------------------begin----------
Breakpoint 1, handle_system_call (dcontext=0x7fff77d534c0) at ./core/dispatch.c:1785
1785	    fcache_enter_func_t fcache_enter = get_fcache_enter_private_routine(dcontext);
(gdb) 
Continuing.
[1]    4495 segmentation fault  gdb --args ./bin64/drrun -debug -loglevel 3 -- signal_SIGALARM
----------------------------end----------

3. more details:
OS: Ubuntu 4.4.0-165-generic #193-Ubuntu SMP 
GDB: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Info 1: The same problem exists when I set breakpoints at the other functions like master_signal_handler_C.
Info 2: Instructions like "mov -0x198(%rbp), %rcx" trigger the segmentation fault. The memory address -0x198(%rbp) is located in a code cache segment with "WR-P" attribute. 
Info 3: Release 7.1.0 doesn't have such a problem.

4. Possible reason:
DynamoRIO may wrongly set the attribute of a  code cache segment at runtime.

Look forward to your response.
Thanks.

**Comment by hgreving2304** [comment] 2019-10-26 17:58
I can't really tell much from above. It might be better to ask dynamorio-devs@googlegroups.com first before filing a bug. Can you share a symbolized backtrace, the logs you got with loglevel 3, and maybe even a reproducer? Just double-checking: you're not talking about these segfaults, are you: https://github.com/DynamoRIO/dynamorio/wiki/Debugging#expected-signals ?

**Comment by derekbruening** [comment] 2019-10-26 17:59
From your output, *gdb* is what crashed, not DR and not the app.

**Comment by derekbruening** [comment] 2019-10-27 19:36
To make sure I was clear, this output:
```
(gdb)
Continuing.
[1] 4495 segmentation fault gdb --args ./bin64/drrun -debug -loglevel 3 -- signal_SIGALARM
----------------------------end----------
```

That output shows gdb crashing and the shell reporting that it crashed with a SIGSEGV.  I.e., this is some bug in gdb itself.  I see no evidence of a DR bug.  I would suggest trying different gdb versions, reporting this to gdb, etc.

**Comment by timhai88** [comment] 2019-10-29 01:36
The execution log on another machine still suffers the same problem.
----------------Begin-----------------------------------
(gdb) b handle_system_call 
Breakpoint 1 at 0x710d0608: file ~/dynamorio/core/dispatch.c, line 1785.
(gdb) c
Continuing.
<(1+x) Handling our fault in a TRY at 0x000000007129bce5>

Breakpoint 1, handle_system_call (dcontext=0x7fff77d534c0) at ~/dynamorio/core/dispatch.c:1785
1785	    fcache_enter_func_t fcache_enter = get_fcache_enter_private_routine(dcontext);
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
handle_system_call (dcontext=0x7fff77d534c0) at ~/dynamorio/core/dispatch.c:1785
1785	    fcache_enter_func_t fcache_enter = get_fcache_enter_private_routine(dcontext);
(gdb) x/4i $pc
=> 0x710d0608 <handle_system_call+19>:	mov    -0xe8(%rbp),%rax
   0x710d060f <handle_system_call+26>:	mov    %rax,%rdi
   0x710d0612 <handle_system_call+29>:	callq  0x712000ca <get_fcache_enter_private_routine>
   0x710d0617 <handle_system_call+34>:	mov    %rax,-0x30(%rbp)
(gdb) x/4gx $rbp-0xe8
0x7fff77da2d68:	0x00007fff77d534c0	0x00007fff77da2e20
0x7fff77da2d78:	0x00000000712b5f4b	0x0000000031014fc8
(gdb) info proc
process 16465
cmdline = 'signal_SIGALARM'
cwd = '~/dynamorio/build_debug'
exe = '~/dynamorio/build_debug/lib64/debug/libdynamorio.so'
(gdb) !cat /proc/16465/maps 
...
7fff77d93000-7fff77d95000 ---p 00000000 00:00 0 
7fff77d95000-7fff77da3000 rw-p 00000000 00:00 0 
7fff77da3000-7fff77da5000 ---p 00000000 00:00 0 
...
(gdb) c
Continuing.
<Application ~/dynamorio/build_debug/signal_SIGALARM (16465).  DynamoRIO internal crash at PC 0x00000000710d0608.  Please report this at http://dynamorio.org/issues/.  Program aborted.
Received SIGSEGV at pc 0x00000000710d0608 in thread 16465
Base: 0x0000000071000000
Registers:eax=0x00007fff77d534c0 ebx=0x00007fff77dc4cd8 ecx=0x0000000000000040 edx=0x0000000000000060
	esi=0x0000000000000002 edi=0x00007fff77d534c0 esp=0x00007fff77da2d60 ebp=0x00007fff77da2e50
	r8 =0x0000000000000001 r9 =0x00000000713310a3 r10=0x00007fff77da1fa0 r11=0x0000000000000246
	r12=0x00007fff77d11000 r13=0x00000000000039a0 r14=0x0000000000000032 r15=0x0000000000000000
	eflags=0x0000000000010206
version 7.91.18192, custom build
-no_dynamic_options -loglevel 3 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0x00007fff77da2e50 0x00000000710c82e4
0x00007fff77da2f10 0x00000000710c3aaf
0x00007fff77da2ff0 0x0000000031009f05>
[Inferior 1 (process 16465) exited with code 0377]
----------------------------end------------------------------

**Comment by timhai88** [comment] 2019-10-29 01:40
Oh, the issue is closed?
I add a new execution log, please check.

Thanks

**Comment by derekbruening** [comment] 2019-10-29 03:49
The issue was closed because no evidence of any DR problem had been provided, as was explained.

Now different symptoms are being presented.

There is not enough information here -- please include context information including:

- Does anything go wrong *outside of gdb*?
- Does anything go wrong inside gdb *with no breakpoints set*?
- What is the actual faulting address of the SIGSEGV at 0x710d0608?  Run `p $_siginfo._sifields._sigfault.si_addr`
- What is this signal_SIGALARM program doing?
- Does anything go wrong with hello,world, or only with this signal_SIGALARM program?

**Comment by timhai88** [comment] 2019-10-29 05:26
- Does anything go wrong outside of gdb?
No. "./bin64/drrun -debug -loglevel 3 -- signal_SIGALARM" runs successfully outside gdb

- Does anything go wrong inside gdb with no breakpoints set?
No. runs successfully if no breakpoints

- actual faulting address
----------------------------Begin--------------------------------------
Program received signal SIGSEGV, Segmentation fault.
handle_system_call (dcontext=0x7fff77d534c0) at ~/dynamorio/core/dispatch.c:1785
1785	    fcache_enter_func_t fcache_enter = get_fcache_enter_private_routine(dcontext);
(gdb) p $_siginfo._sifields._sigfault
$1 = {si_addr = 0x7ffff7c207be, _addr_lsb = 6308747, _addr_bnd = {_lower = 0x7fff00000003, 
    _upper = 0x7fffffffd3c0}}

(gdb) x/4i $pc-7
   0x710d0601 <handle_system_call+12>:	mov    %rdi,-0xe8(%rbp)
=> 0x710d0608 <handle_system_call+19>:	mov    -0xe8(%rbp),%rax
   0x710d060f <handle_system_call+26>:	mov    %rax,%rdi
   0x710d0612 <handle_system_call+29>:	callq  0x712000ca <get_fcache_enter_private_routine>

(gdb) p $rbp-0xe8
$2 = (void *) 0x7fff77da2d68

(gdb) ! cat /proc/30181/maps 
... 
7fff77d93000-7fff77d95000 ---p 00000000 00:00 0 
7fff77d95000-7fff77da3000 rw-p 00000000 00:00 0 
7fff77da3000-7fff77da5000 ---p 00000000 00:00 0 
... 
7fff77dd3000-7ffff7d16000 ---p 00000000 00:00 0 
7ffff7d16000-7ffff7d3c000 r-xp 00000000 08:07 289045                     /lib/x86_64-linux-gnu/ld-2.23.so
7ffff7d3c000-7ffff7f3b000 ---p 00000000 00:00 0
...
----------------------------End--------------------------------------

- signal_SIGALARM.c
-----------------------------------------------Begin-------------------
int main(int argc, char *argv[])
{
    ...
    sVal.sa_sigaction = HandleSignal;
    ...

    locked = 1;
    alarm(2);
    while (locked){}

    ...
}

void HandleSignal(int sig, siginfo_t *si, void *context)
{
    switch (sig)
    {   
        case SIGALRM:
            locked = 0;
            break;
    }   
}
------------------------------------------end-------------------------------

- Run Hello_world
Exactly the same problem, the same si_addr

Thanks

**Comment by derekbruening** [comment] 2019-10-29 14:43
(Use triple backticks on a line by themselves to delineate a verbatim region -- I edited yours to do this and make it easier to read.)

So the faulting address 0x7ffff7c207be has no apparent relationship to the instruction at $pc nor the previous instruction?  It seems unrelated to both the instruction fetch addresses for the current and previous instructions and to the loads and stores they perform.  Was it synthetic, generated not by hardware but by the kernel?  Look at the other `$_siginfo` fields to determine its source.

**Comment by derekbruening** [comment] 2019-10-29 14:45
Also, make sure your backward disassembly got the right prior instruction, by disassembling that function from the start.  It looks reasonable, but just to be sure.

**Comment by derekbruening** [comment] 2019-10-29 14:46
If this is not some synthetic SIGSEGV, I would next try:

- Use a watchpoint instead of a breakpoint to break at the same place.  Does the SIGSEGV still happen then?
- Try a different version of gdb, or a different debugger.  What version of gdb is this?

**Comment by timhai88** [comment] 2019-10-30 02:38
1. Please note that 0x7ffff7c207be is within address space neither readable nor writable. It is hard to explain why the code touch this address.
```
7fff77dd3000-7ffff7d16000 ---p 00000000 00:00 0
```
2. Disassembly codes start from the beginning of the function:
```
(gdb) x/20i master_signal_handler_C
   0x712daac1 <master_signal_handler_C>:	push   %rbp
   0x712daac2 <master_signal_handler_C+1>:	mov    %rsp,%rbp
   0x712daac5 <master_signal_handler_C+4>:	push   %rbx
   0x712daac6 <master_signal_handler_C+5>:	sub    $0x188,%rsp
   0x712daacd <master_signal_handler_C+12>:	mov    %edi,-0x174(%rbp)
   0x712daad3 <master_signal_handler_C+18>:	mov    %rsi,-0x180(%rbp)
   0x712daada <master_signal_handler_C+25>:	mov    %rdx,-0x188(%rbp)
   0x712daae1 <master_signal_handler_C+32>:	mov    %rcx,-0x190(%rbp)
=> 0x712daae8 <master_signal_handler_C+39>:	mov    -0x190(%rbp),%rax
   0x712daaef <master_signal_handler_C+46>:	mov    %rax,-0x40(%rbp)
```
3. Detailed _siginfo:
```
(gdb) p/x $_siginfo
$2 = {si_signo = 0xb, si_errno = 0x0, si_code = 0x2, _sifields = {_pad = {0xf7c207be, 0x7fff, 0x10238d0, 0x0, 0xf5ee3b58, 0x7fff, 0xffffd280, 0x7fff, 0xf5ee3b70, 0x7fff, 0x2d81, 0xffff8000, 0xffffd27f, 
      0x7fff, 0x597888, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf0e630, 0x0, 0xd0cbd0, 0x0, 0xffffd564, 0x7fff}, _kill = {si_pid = 0xf7c207be, si_uid = 0x7fff}, _timer = {si_tid = 0xf7c207be, 
      si_overrun = 0x7fff, si_sigval = {sival_int = 0x10238d0, sival_ptr = 0x10238d0}}, _rt = {si_pid = 0xf7c207be, si_uid = 0x7fff, si_sigval = {sival_int = 0x10238d0, sival_ptr = 0x10238d0}}, 
    _sigchld = {si_pid = 0xf7c207be, si_uid = 0x7fff, si_status = 0x10238d0, si_utime = 0xf5ee3b5800000000, si_stime = 0xffffd28000007fff}, _sigfault = {si_addr = 0x7ffff7c207be, _addr_lsb = 0x10238d0, 
      _addr_bnd = {_lower = 0x7ffff5ee3b58, _upper = 0x7fffffffd280}}, _sigpoll = {si_band = 0x7ffff7c207be, si_fd = 0x10238d0}}}
```

**Comment by timhai88** [comment] 2019-10-30 02:49
1. Hardware breakpoint also triggers the same problem:
```
Program received signal SIGSEGV, Segmentation fault.
handle_system_call (dcontext=0x7fff77d534c0) at ~/dynamorio/core/dispatch.c:1785
1785	    fcache_enter_func_t fcache_enter = get_fcache_enter_private_routine(dcontext);

(gdb) info b
Num     Type           Disp Enb Address            What
1       hw breakpoint  keep y   0x00000000710d0608 in handle_system_call at ~/dynamorio/core/dispatch.c:1785
	breakpoint already hit 1 time

(gdb) x/4i $pc-7
   0x710d0601 <handle_system_call+12>:	mov    %rdi,-0xe8(%rbp)
=> 0x710d0608 <handle_system_call+19>:	mov    -0xe8(%rbp),%rax
   0x710d060f <handle_system_call+26>:	mov    %rax,%rdi
   0x710d0612 <handle_system_call+29>:	callq  0x712000ca <get_fcache_enter_private_routine>
```
2. GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1

**Comment by derekbruening** [comment] 2019-10-30 14:23
It sure looks like a gdb bug to me.  Closing as such.

**Closed by derekbruening** 2019-10-30 14:23 UTC
Labels: Bug-AppFail, OpSys-Linux, OpSys-UNIX, Status-NeedInfo
