### ISSUE TITLE
drcov not executing exe (7.1.0-1)

### ISSUE THREAD

**Issue by elijahlord** [DynamoRIO/dynamorio#3951] opened 2019-11-19 15:16 UTC
**Describe the bug**
drcov seems to crash when run. when i execute any exe with drcov using the command ".\drrun.exe -t drcov -- C:\myprogram.exe" it hangs for a second then just returns to the command line. ive tried it with 10 different executables and they all did that.

**To Reproduce**
i just attempt to run an exe with drcov and it doesnt run

Please also answer these questions:
 - What happens when you run without any client?
im not sure what you mean "without any client". im running standalone exes from the windows command line
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
it gives me an error. i attached the error in the screenshot section

**Expected behavior**
drcov would run as normal and the exe would run

**Screenshots or Pasted Text**
![image](https://user-images.githubusercontent.com/21037707/69158842-dea84600-0a9b-11ea-92ce-5e788a28c301.png)

**Versions**
 - What version of DynamoRIO are you using?
7.1.0-1
 - Does the latest build from
https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build solve the problem?
no
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
windows 10 Version 10.0.18362 Build 18362

- Is your application 32-bit or 64-bit?
32 bit

**Additional context**

**Comment by derekbruening** [comment] 2019-11-19 15:39
> Does the latest build from
https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build solve the problem?
> no

Are you sure?  This callback.c:3780 assert is #3391 which was fixed when 1809 support was added in February, so this is almost certainly a duplicate of #3391.  Please try a more recent cronbuild.

Xref the same issue on the users list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dynamorio-users/YGEh5ZmnfGw/DzRAPBVUAgAJ.

**Closed by derekbruening** 2019-11-19 15:39 UTC
