### ISSUE TITLE
DynamoRIO can have unbounded signal delivery time when a signal arrives during cache entry

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2019] opened 2016-10-12 16:41 UTC
You probably knew that, but here is a program that demonstrates it, repeatably.

The way I have solved this problem in other projects is as follows:

If a signal arrives while the PC is in the fragment cache, we handle it immediately. If a signal arrives while we are in the runtime, we set a flag which gets checked as we return to the fragment cache. DynamoRIO does this, I think, with dcontext->signals_pending being the flag.

The problem, of course, is a signal arriving after you've checked the flag but before you arrive in the fragment cache. The solution is to write this part, from checking the flag up to the final branch into the fragment cache, in assembler so that the master signal handler can recognise those PC values.

What does the master signal handler do when it recognises a PC value in that region? Two possibilities:

1. It knows the code was loading the register state from some structure, so it just gets the state from that structure and then longjmps somewhere or something...

2. It knows that the code region is restartable, so it sets the flag, resets the PC to the start of the region, and returns (from the signal handler). The assembler code then sees that the flag is set and returns to the C runtime. I call a restartable code region like this a "ramp". Its advantage is simplicity: a signal that arrives while you're on the ramp can be handled in exactly the same way as a signal that arrives while you're in the C runtime, so you don't have a rarely visited code path that needs separate testing.

I'm not sure how practicable it would be to combine fully race-free signal handling with client instrumentation...

```
/* **********************************************************
 * Copyright (c) 2016 ARM Limited. All rights reserved.
 * **********************************************************/

/*
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of ARM Limited nor the names of its contributors may be
 *   used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL ARM LIMITED OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

/* Repeatedly set a short-duration timer, adjusting it to arrive immediately
 * after the return from the system call. This can expose a race condition.
 */

#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

volatile int polling_started;
volatile int signal_arrived;
timer_t timer;

void fail(const char *s)
{
    perror(s);
    exit(1);
}

void handler(int signum)
{
    signal_arrived = 1;
}

void setup(void)
{
    struct sigaction act;
    struct sigevent sevp;

    memset(&act, 0, sizeof(act));
    act.sa_handler = handler;
    if (sigaction(SIGUSR1, &act, 0))
        fail("sigaction");

    memset(&sevp, 0, sizeof(sevp));
    sevp.sigev_notify = SIGEV_SIGNAL;
    sevp.sigev_signo = SIGUSR1;
    if (timer_create(CLOCK_REALTIME, &sevp, &timer))
        fail("timer_create");
}

int try(uint64_t time)
{
    struct itimerspec spec = {
        { 0, 0 },
        { time / 1000000000, time % 1000000000 }
    };
    polling_started = 0;
    signal_arrived = 0;
    if (timer_settime(timer, 0, &spec, 0))
        fail("timer_settime");
    if (!signal_arrived) {
        polling_started = 1;
        while (!signal_arrived)
            ;
    }
    return polling_started;
}

int main()
{
    int counts[2] = { 0, 0 };
    uint64_t time = 1;
    uint64_t step = 1;
    int direction = 0;
    int count_max = 4;
    int count = count_max;
    int i;

    setup();
    for (i = 0; i < 10000; i++) {
        printf("%8d %llu\n", i, (unsigned long long)time);
        int r = try(time);
        ++counts[r];

        /* Count number of successive steps in same direction. */
        if (r == direction)
            count = count >= count_max ? count_max : count + 1;
        else
            count = 0;
        direction = r;

        /* Halve or double step. */
        if (count < count_max - 1)
            step = step >> 1 ? step >> 1 : 1;
        else if (count >= count_max)
            step = step << 1 ? step << 1 : step;

        /* Adjust time, avoiding zero and overflow. */
        if (direction) {
            if (step < time)
                time -= step;
            else {
                time = 1;
                step = 1;
            }
        }
        else {
            if (time + step > time)
                time += step;
            else {
                time = -1;
                step = 1;
            }
        }
    }
    printf("Summary: %d %d %d\n", counts[0], counts[1], (int)time);
    return 0;
}
```

**Comment by derekbruening** [comment] 2016-10-12 17:12
Please clarify: what behavior under DR are you seeing that is incorrect.  A signal being dropped b/c there's already a queued signal of the same (non-real-time) type is not incorrect behavior.

**Comment by egrimley** [comment] 2016-10-12 17:17
The program runs to completion natively, but gets stuck in an infinite loop under DynamoRIO. Is a signal arriving when a signal is already queued? I hope not. That's not the intention.

**Comment by derekbruening** [comment] 2016-10-12 17:32
Are you sure the program is correct and robust natively and that it doesn't just happen to work with native timing?  There are no guarantees on precisely when signals are delivered.  Are you sure that slowing down parts of the program through some other non-DR mechanism wouldn't also make it misbehave?

**Comment by derekbruening** [comment] 2016-10-12 17:34
Basically I'm confused as to where you're saying DR is "missing a signal".  An incoming (non-RT) signal is only dropped when there's already a queued signal of the same number.

**Comment by derekbruening** [comment] 2016-10-12 19:10
I also don't follow the reason for the discussion on flag checking or recognizing assembly: I don't see how they apply or are necessary for DR.  When a signal arrives, there are checks for whether it's in the cache, but if it's anywhere else that's all considered "must delay", so that discussion just doesn't seem to apply.  Please elaborate on what you're seeing in DR that looks incorrect.

**Comment by egrimley** [comment] 2016-10-12 19:29
The program is intended to be natively robust... What seems to happen is that the app goes into an infinite loop in the fragment cache waiting for a volatile variable to be set by the signal handler, but the app's signal handler never gets invoked because DR only checks signals_pending when it returns to the runtime, which it never does. Delaying the delivery of a signal for ever is presumably incorrect. (Detecting it a long time later with some kind of timer signal would be a rubbishy solution.)

**Comment by derekbruening** [comment] 2016-10-13 02:26
I see, I understand now, thank you for elaborating: so it's not missing receipt of a signal, it's not delivering it in bounded time due to not unlinking the being-entered fragment.  There are some other worries about bounded delivery, including arrival in the ibl, that are briefly mentioned in the code from a long time ago, but nothing that I know of officially in the tracker.

**Comment by derekbruening** [comment] 2016-10-14 16:33
The solution should be pretty straightforward: simply call unlink_fragment_for_syscall to do the unlink and inlined syscall skip for fragments that match dcontext->next_tag and ecx (for ibl).

**Comment by derekbruening** [comment] 2016-10-17 23:13
I will try this proposed solution for gencode matches, plus another flag check at fcache entry (the current one is at exit).

**Comment by egrimley** [comment] 2016-10-18 13:27
I would guess that unlinking fragments would have a much greater overhead than the "ramp" approach, and I'm not sure how what you're suggesting could be generalised to other signal race situations, such as i#2025.

**Comment by derekbruening** [comment] 2016-10-18 14:51
#2025 is the same race: no generalizing is needed.  The mechanism for exiting the cache in order to call the app's signal handler when a signal arrives in the middle of a fragment that is either going to loop or is going to make a syscall is to unlink the fragment so that it skips the loop/syscall.  The problem is that today a signal that arrives while on the way to that fragment (in fcache_enter gencode or ibl gencode) does not unlink it.

**Comment by egrimley** [comment] 2016-10-18 15:01
> #2025 is the same race: no generalizing is needed. The mechanism for exiting the cache in order to call the app's signal handler when a signal arrives in the middle of a fragment that is either going to loop or is going to make a syscall is to unlink the fragment so that it skips the loop/syscall. The problem is that today a signal that arrives while on the way to that fragment (in fcache_enter gencode or ibl gencode) does not unlink it.

Doesn't that rather depend on which syscall? There seem to be plenty
of places where the runtime invokes dynamorio_syscall.

Unlinking fragments means flushing the cache, right? Perhaps that
gives acceptable performance on Intel, but I would rather avoid it on
ARM.

**Comment by derekbruening** [comment] 2016-10-18 15:04
> Doesn't that rather depend on which syscall? There seem to be plenty
> of places where the runtime invokes dynamorio_syscall.

I don't see how the runtime's invocation of syscalls on its own behalf would be involved here.

> Unlinking fragments means flushing the cache, right?

No.  It's just a couple of atomic writes.

**Comment by egrimley** [comment] 2016-10-18 15:14
> Doesn't that rather depend on which syscall? There seem to be plenty
> of places where the runtime invokes dynamorio_syscall.
>
> I don't see how the runtime's invocation of syscalls on its own behalf would be involved here.

I'll get back to you later about that... Must run now...

> Unlinking fragments means flushing the cache, right?
>
> No. It's just a couple of atomic writes.

So not writes of instructions then?

**Comment by derekbruening** [comment] 2016-10-18 15:39
> > > Unlinking fragments means flushing the cache, right?

> > No. It's just a couple of atomic writes.

> So not writes of instructions then?

If you mean flushing the software code cache (as I read it), no there is no such flush to unlink fine-grained fragments.

If you mean the hardware icache, it is writing code, and for both x86 and ARM a cache line will be invalidated.

To do otherwise would be a significant design change regarding precise translation points and resumption points in a volatile code cache.

**Comment by egrimley** [comment] 2016-10-18 16:30
> If you mean the hardware icache, it is writing code, and for both x86 and ARM a
> cache line will be invalidated.
> 
> To do otherwise would be a significant design change regarding precise
> translation points and resumption points in a volatile code cache.

It would be interesting to measure the performance cost. Which is the
fastest system call for which this happens, do you think?

Edmund

**Closed** 2016-10-23 00:43 UTC
Labels: OpSys-Linux

**Comment by egrimley** [comment] 2016-11-03 15:11
With DEBUG, the signal_race test usually fails for me on Debian armhf stretch on APM Mustang.
Without DEBUG it usually passes, but sometimes fails, particularly if I do other work on the machine.
The failure is an infinite loop, consistent with the delivery of the signal being delayed indefinitely.

**Comment by derekbruening** [comment] 2016-11-03 15:16
Are you just hitting #2042?
