### ISSUE TITLE
tool.drcachesim.opcode_mix failed on x86-32

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#6314] opened 2023-09-19 02:06 UTC
tool.drcachesim.opcode_mix failed on the x86-32 run on PR #6313:
https://github.com/DynamoRIO/dynamorio/actions/runs/6227837689/job/16903332100?pr=6313

```
302/412 Test #302: code_api|tool.drcachesim.opcode_mix ..............................***Failed  Required regular expression not found. Regex=[^Hello, world!
---- <application exited with code 0> ----
Opcode mix tool results:
    *[0-9]* : total executed instructions
    *[0-9]* : [a-z ]*
    *[0-9]* : [a-z ]*
    *[0-9]* : [a-z ]*
    *[0-9]* : [a-z ]*
.*
$
]  2.86 sec
Hello, world!
Encoding size 2 != instr size 6
drcachesim: /home/runner/work/dynamorio/dynamorio/clients/drcachesim/reader/reader.cpp:203: virtual bool dynamorio::drmemtrace::reader_t::process_input_entry(): Assertion `false' failed.
```

Didn't happen when I re-ran the workflow.

**Comment by derekbruening** [comment] 2023-09-19 03:36
Duplicate of #6303?

**Comment by abhinav92003** [comment] 2023-09-19 16:11
> Duplicate of #6303?

Looks like it. Perhaps this one should be closed then.

I added a comment mentioning "opcode_mix" to #6303 and tried searching for "opcode_mix" on Github but #6303 didn't turn up in the result. Maybe we should add it to the name of the issue? But then how does this strategy work with failures that happen on many tests.

**Comment by derekbruening** [comment] 2023-09-19 16:27
I think the important part is to put the reason the test failed in the title and search for that.

**Closed by derekbruening** 2023-09-19 16:27 UTC
Labels: Component-Tests, OpSys-x86
