### ISSUE TITLE
[drrun] DynamoRIO usage error : Failed to read app ELF headers.  Check path and architecture.>

### ISSUE THREAD

**Issue by rkgithubs** [DynamoRIO/dynamorio#3569] opened 2019-04-22 20:53 UTC
I'm using DynamoRIO-x86_64-Linux-7.90.17998-0 which seems latest. 
When i ran it with the sample application (linux perf tool) it failed due to the following error: 

/DynamoRIO-x86_64-Linux-7.90.17998-0/bin64$ ./drrun -t drcachesim -offline -- perf top
<Application /usr/bin/perf (18398) DynamoRIO usage error : Failed to read app ELF headers.  Check path and architecture.>

PERF loads the ELF header first instead of loading entire library, it is expected behavior but the tool fails to recognize it and ASSERTS error for it. This issue seems similar to #1240.  
Seems to encounter the same issue with few other applications.

**Comment by derekbruening** [comment] 2019-04-22 23:45
No I do not think this has anything to do with what perf is doing: it's that perf is a bash script.  It works fine if I run `/bin/bash` explicitly:

```
 bin64/drrun -- perf --help
<Application /usr/bin/perf (65089) DynamoRIO usage error : Failed to read app ELF headers.  Check path and architecture.>
<Usage error: Failed to read app ELF headers.  Check path and architecture. (/home/bruening/dr/git/src/core/unix/loader.c, line 1844)
version 7.90.18005, custom build
-early_inject 
0x00007ffde46a06c0 0x00007fef14d466c0
0x00007ffde46a0710 0x00007fef14f44ddd
0x00007ffde46a1380 0x00007fef14ef4f64>

$ bin64/drrun -- /bin/bash /usr/bin/perf --help
<Starting application /bin/bash (65178)>
<Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/bruening/dr/git/build_x64_dbg_tests/lib64/debug/libdynamorio.so' 0x00007ff798b40b20
>
<(1+x) Handling our fault in a TRY at 0x00007ff798d8a459>
<spurious rep/repne prefix @0x00007ff7988ffe58 (f2 41 ff e3): >
<-- parent 65178 forked child 65187 -->
<-- execve /bin/uname -->
<Starting application /bin/uname (65187)>
<Initial options = -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/bruening/dr/git/build_x64_dbg_tests/lib64/debug/libdynamorio.so' 0x00007f2ab78e4b20
>
<(1+x) Handling our fault in a TRY at 0x00007f2ab7b2e459>
<spurious rep/repne prefix @0x00007f2ab76a3e58 (f2 41 ff e3): >
<Stopping application /bin/uname (65187)>
<-- execve /usr/bin/perf_4.19 -->
<Starting application /usr/bin/perf_4.19 (65178)>
<Initial options = -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/bruening/dr/git/build_x64_dbg_tests/lib64/debug/libdynamorio.so' 0x00007fbe2f3edb20
>
<(1+x) Handling our fault in a TRY at 0x00007fbe2f637459>
<spurious rep/repne prefix @0x00007fbe2f1ace58 (f2 41 ff e3): >

 usage: perf [--version] [--help] [OPTIONS] COMMAND [ARGS]

 The most commonly used perf commands are:
   annotate        Read perf.data (created by perf record) and display annotated code
...
 See 'perf help COMMAND' for more information on a specific command.

<Stopping application /usr/bin/perf_4.19 (65178)>
```

This looks like a duplicate of #3115.

**Closed by derekbruening** 2019-04-22 23:45 UTC
