### ISSUE TITLE
tool.drcachesim.scattergather failing on x86-32

### ISSUE THREAD

**Issue by prasun3** [DynamoRIO/dynamorio#5806] opened 2022-12-28 08:02 UTC
The failure is because the line `AVX2/AVX-512 scatter/gather checks ok` is missing in the test output. Seen in #5805 

```
UpdateCTestConfiguration  from :/home/prasun/dynamorio-latest/build-x86-32/DartConfiguration.tcl
Parse Config file:/home/prasun/dynamorio-latest/build-x86-32/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/prasun/dynamorio-latest/build-x86-32/DartConfiguration.tcl
Parse Config file:/home/prasun/dynamorio-latest/build-x86-32/DartConfiguration.tcl
Test project /home/prasun/dynamorio-latest/build-x86-32
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 282
    Start 282: code_api|tool.drcachesim.scattergather

282: Test command: /home/prasun/dynamorio-latest/build-x86-32/bin32/drrun "-s" "90" "-quiet" "-killpg" "-stderr_mask" "0xC" "-dumpcore_mask" "0" "-code_api" "-t" "drcachesim" "-ipc_name" "/home/prasun/dynamorio-latest/build-x86-32/suite/tests/drtestpipe_scattergather" "-simulator_type" "basic_counts" "--" "/home/prasun/dynamorio-latest/build-x86-32/suite/tests/bin/client.drx-scattergather"
282: Test timeout computed to be: 1500
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: AVX2 gather ok
282: Test updating the AVX2 gather mask register upon translation events
282: Test restoring the AVX2 gather scratch xmm register upon a fault
282: ---- <application exited with code 139> ----
282: Basic counts tool results:
282: Total counts:
282:       239145 total (fetched) instructions
282:         9401 total unique (fetched) instructions
282:          759 total non-fetched instructions
282:            0 total prefetches
282:        76560 total data loads
282:        41528 total data stores
282:            0 total icache flushes
282:            0 total dcache flushes
282:            1 total threads
282:         1588 total scheduling markers
282:            0 total transfer markers
282:            0 total function id markers
282:            0 total function return address markers
282:            0 total function argument markers
282:            0 total function return value markers
282:            0 total physical address + virtual address marker pairs
282:            0 total physical address unavailable markers
282:            4 total other markers
282:            0 total encodings
282: Thread 120268 counts:
282:       239145 (fetched) instructions
282:         9401 unique (fetched) instructions
282:          759 non-fetched instructions
282:            0 prefetches
282:        76560 data loads
282:        41528 data stores
282:            0 icache flushes
282:            0 dcache flushes
282:         1588 scheduling markers
282:            0 transfer markers
282:            0 function id markers
282:            0 function return address markers
282:            0 function argument markers
282:            0 function return value markers
282:            0 physical address + virtual address marker pairs
282:            0 physical address unavailable markers
282:            4 other markers
282:            0 encodings
1/1 Test #282: code_api|tool.drcachesim.scattergather ...***Failed  Required regular expression not found.Regex=[^AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
AVX2 gather ok
Test updating the AVX2 gather mask register upon translation events
Test restoring the AVX2 gather scratch xmm register upon a fault
AVX2/AVX-512 scatter/gather checks ok
---- <application exited with code 0> ----
Basic counts tool results:
Total counts:
     .* total \(fetched\) instructions
     .* total unique \(fetched\) instructions
     .* total non-fetched instructions
     .* total prefetches
     .* total data loads
     .* total data stores
     .* total icache flushes
     .* total dcache flushes
           1 total threads
     .* total scheduling markers
     .* total transfer markers
     .* total function id markers
     .* total function return address markers
     .* total function argument markers
     .* total function return value markers
     .* total physical address \+ virtual address marker pairs
     .* total physical address unavailable markers
     .* total other markers
     .* total encodings
Thread .* counts:
     .* \(fetched\) instructions
     .* unique \(fetched\) instructions
     .* non-fetched instructions
     .* prefetches
     .* data loads
     .* data stores
     .* icache flushes
     .* dcache flushes
     .* scheduling markers
     .* transfer markers
     .* function id markers
     .* function return address markers
     .* function argument markers
     .* function return value markers
     .* physical address \+ virtual address marker pairs
     .* physical address unavailable markers
     .* other markers
     .* encodings
$
]  0.53 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   4.43 sec

The following tests FAILED:
	282 - code_api|tool.drcachesim.scattergather (Failed)
```

**Comment by abhinav92003** [comment] 2023-01-06 16:43
This looks like a duplicate of #5747.

**Closed by abhinav92003** 2023-01-06 16:43 UTC
