### ISSUE TITLE
ASSERT: multi client use fails in DR 8 and 9

### ISSUE THREAD

**Issue by mewais** [DynamoRIO/dynamorio#6109] opened 2023-06-05 09:02 UTC
**Describe the bug**
As the title shows. Multi client use fails does not work in DR.

**To Reproduce**
To reproduce, use the following command using dynamorio's sample clients:
```
drrun -client libinscount.so 0 "" -client libbbcount.so 1 "" -- ls
```

**Expected behavior**
Both clients should work fine, and display their count of instructions and BBs.

**Screenshots or Pasted Text**
Running the command `/home/mewais/DynamoRIO-8/bin64/drrun -client /home/mewais/DynamoRIO-8/samples/debug/bin/libinscount.so 0 "" -client /home/mewais/DynamoRIO-8/samples/debug/bin/libbbcount.so 1 "" -- ls` yields the following output:
```
<Application /usr/bin/ls (290463).  DynamoRIO internal crash at PC 0x000000007113730d.  Please report this at http://dynamorio.org/issues/.  Program aborted.
Received SIGSEGV at unknown pc 0x000000007113730d in thread 290463
Base: 0x0000000071000000
Registers:eax=0x00007f0ed15f5860 ebx=0x00007f0ed1600c80 ecx=0x00007ffc6040f99f edx=0x00007f0f51a398aa
	esi=0x00007f0f51a376e8 edi=0x0000000000000000 esp=0x00007ffc6040f990 ebp=0x0000000000000000
	r8 =0x000000000000118e r9 =0x0000000000000007 r10=0x0000000000000043 r11=0x0000000000217a08
	r12=0x00007f0f51a398aa r13=0x00007f0ed15f5860 r14=0x00007ffc6040f99f r15=0x0000000000000000
	eflags=0x0000000000010206
version 8.0.0, build 1
-no_dynamic_options -client_lib '/home/mewais/DynamoRIO-8/samples/debug/bin/libinscount.so;0;;/home/mewais/DynamoRIO-8/samples/debug/bin/libbbcount.so;1;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list ''
0x00000000713d849d 0x6974706f5f63696d>
```

Enabling the `-debug` options changes the output to the following:
```
<Starting application /usr/bin/ls (290464)>
<Initial options = -no_dynamic_options -client_lib '/home/mewais/DynamoRIO-8/samples/debug/bin/libinscount.so;0;;/home/mewais/DynamoRIO-8/samples/debug/bin/libbbcount.so;1;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Application /usr/bin/ls (290464).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/module_elf.c:1131 pd != NULL && name != NULL
(Error occurred @0 frags)
version 8.0.0, build 1
-no_dynamic_options -client_lib '/home/mewais/DynamoRIO-8/samples/debug/bin/libinscount.so;0;;/home/mewais/DynamoRIO-8/samples/debug/bin/libbbcount.so;1;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list ''
0x00007ffd4c082df0 0x00000000710dc095
0x00007ffd4c083040 0x00000000712f7445
0x00007ffd4c083130 0x00000000712f8616
0x00007ffd4c0831a0 0x00000000712f888a
0x00007ffd4c0831e0 0x00000000712edee6
0x00007ffd4c083200 0x00000000712ee0ae
0x00007ffd4c083230 0x00000000712ec614
0x00007ffd4c083290 0x00000000711d8fe8
0x00007ffd4c0832b0 0x00000000711d889f
0x00007ffd4c083310 0x00000000712ecbc9
0x00007ffd4c083540 0x00000000712ec5b3
0x00007ffd4c0835a0 0x00000000711d8fe8
0x00007ffd4c0835c0 0x00000000711d889f
0x00007ffd4c083620 0x00000000712ecbc9
0x00007ffd4c083850 0x00000000712ec5b3
/home/mewais/DynamoRIO-8/samples/debug/bin/libbbcount.so=0x00007f9771f61000
/home/mewais/DynamoRIO-8/ext/lib64/debug/libdrx.so=0x00007f9771fae000
/home/mewais/DynamoRIO-8/ext/lib64/debug/libdrreg.so=0x00007f97721c1000
/home/mewais/DynamoRIO-8/ext/lib64/debug/libdrmgr.so=0x00007f97723ce000
/home/mewais/DynamoRIO-8/samples/debug/bin/libinscount.so=0x00007f9771f57000>
```

**Versions**
This was tested with DynamorRIO 8.0.0-1, but it also occured with 9.0.1
I am running on 64-bit Ubuntu 22.04.2 kernel version 5.11.0-49-generic

**Comment by derekbruening** [comment] 2023-06-05 15:40
As noted in the users list thread that preceded this issue https://groups.google.com/g/dynamorio-users/c/8VLtsx6cXls this is likely a regression from Linux loader initialization order changes (a binary search should pintpoint the exact commit and point to the fix).  It looks like there is no current test of multiple clients which is surprising.  Probably the fix for this is straightforward (and should include adding a test) but given that nobody ended up noticing, this multi-client feature does not seem a high priority.  If someone is interested in using it and helping out by fixing this and added a test that would be great.

**Comment by egrimley-arm** [comment] 2023-10-24 07:43
The commit that caused this regression seems to be 9293e7ae7709ee78fe520722dbe062b8680126d6.

**Comment by AssadHashmi** [comment] 2023-10-24 13:53
This looks like a duplicate of https://github.com/DynamoRIO/dynamorio/issues/4501.

**Closed** 2023-10-24 16:57 UTC
Labels: Status-Duplicate, help wanted
