### ISSUE TITLE
Make MAX_CONTEXT_SIZE dynamically sized to future-proof it

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2666] opened 2017-10-20 01:06 UTC
On Skylake this assert fires:

```
Internal Error: DynamoRIO debug check failure: D:\dynamorio_package\core\win32\ntdll.c:5359 res >= 0 && len <= MAX_CONTEXT_SIZE
```

Xref #1937 for the corresponding Linux signal context issue.
We need to make MAX_CONTEXT_SIZE be dynamically sized.

**Comment by newgre** [comment] 2017-10-24 16:49
For the record: the extended context size for both, Skylake and Kaby Lake, is 0x4F7.
Would you be ok with an update to MAX_CONTEXT_SIZE until dynamic context size has been implemented?

**Comment by newgre** [comment] 2017-10-24 16:59
err, above size was the result without CONTEXT_XSTATE. The correct value should be 0x6EF and 0x4E3 for a 32-bit process.

**Comment by derekbruening** [comment] 2017-10-24 17:48
> Would you be ok with an update to MAX_CONTEXT_SIZE until dynamic context size has been implemented?

Yes that's a reasonable short-term fix.   The current value in the code today for 64-bit MAX_CONTEXT_SIZE is 0x6ef and for 32-bit 0x4e3 -- are you reporting a subset of the context above?
  Your values above wouldn't have triggered the assert.

**Comment by newgre** [comment] 2017-10-24 17:49
in 7 RC1 I see 0x680 and 0x480, respectively, defined in os_private.h?

**Comment by derekbruening** [comment] 2017-10-24 17:50
> Would you be ok with an update to MAX_CONTEXT_SIZE until dynamic context size has been implemented?

The only concern here is that stack buffers of this size are used in a number of places in the code and DR has a limited stack size.  If the MAX_CONTEXT_SIZE gets too much larger they will need to be changed to use the heap.

**Comment by derekbruening** [comment] 2017-10-24 17:53
> in 7 RC1 I see 0x680 and 0x480, respectively, defined in os_private.h?

Ah ok, I'm looking at the latest, and it was updated in 5eebc95e587b9753cacf58bec4b48a4d4c4b2813.  So perhaps the short-term fix has already been done?

**Comment by newgre** [comment] 2017-10-24 17:55
Oh neat, yes those values are the same that I deduced. Are there nightly builds?

**Comment by newgre** [comment] 2017-10-24 17:59
found them: https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build

**Comment by newgre** [comment] 2017-10-24 18:01
no windows builds?

**Comment by derekbruening** [comment] 2017-10-24 18:01
Unfortunately the old Cr nightly builds no longer exist (we should update that wiki page) and noone has set them up with Appveyor yet (#1967)

**Comment by newgre** [comment] 2017-10-24 18:35
I can confirm that the context size related bug is fixed in trunk.

**Comment by securitykernel** [comment] 2019-11-27 13:34
Got here via #3923. I tried launching drrun and drmemory via windbg from cygwin, from within windbg, loading symbols to find out the value of `len` in `ntdll.c:5221`, but all attempts fail, I get access violations, breakpoints fail to trigger, symbols fail to load, etc.

If you can provide a source code snippet that I can compile with VS 2013 to call RtlGetExtendedContextLength() on my system, than I'd be happy to compile and run it.

**Comment by lieser** [comment] 2020-01-15 15:38
On the system that @securitykernel tried the context size seems to be `0xd2f`.

![image](https://user-images.githubusercontent.com/4419226/72447192-2d7d0e00-37b5-11ea-886d-907799b118ae.png)

**Comment by lieser** [comment] 2020-02-19 14:18
@derekbruening Is there any plan to increase the `MAX_CONTEXT_SIZE` further? Nothing urgent as we currently use a local build there we changed the size, but would be nice to get back to an official build in the long run.

**Comment by derekbruening** [comment] 2020-02-19 14:38
Happy to take a pull request for either a short-term size increase or long-term switch to dynamic sizing.

**Comment by ntfshard** [comment] 2020-11-12 15:58
This trouble is still reproducible, is it possible to workaround somehow on my side?

**Comment by derekbruening** [comment] 2020-11-13 14:42
> This trouble is still reproducible, is it possible to workaround somehow on my side?

You can see all the discussion above about local builds and changing the constant (and longer-term refactoring).  It would be awesome if someone with these affected machine environments who can thus test it were able to send a pull request for at least a short-term fix.

**Comment by lieser** [comment] 2020-11-13 15:38
For reference, here are the notes I took then I debugged it on our affected machine to get the needed value. Note that it has been some time since I did it, so no guarantee about correctness/completes about them:

All done with WinDbg and a cronbuild from https://github.com/DynamoRIO/dynamorio/releases:

As the automatic loading of symbols described at https://github.com/DynamoRIO/dynamorio/wiki/Debugging#debugging-on-windows did nor work for use, we had to load the symbols manually (adapt paths below):
```
.sympath+ C:\<path>\DynamoRIO-Windows\lib64\debug;C:\<path>\DynamoRIO-Windows\lib64
.reload dynamorio.dll=15000000
```

To get to the nt_initialize_context function (e.g. to get the value on a system that does not trigger the assert), execute the following afterwards:
```
.childdbg 1
g
$$ should now be at the running process, e.g. notepad
bp dynamorio!nt_initialize_context
g
```
Afterwards, make a few manual single steps, until the `len` variable gets populated with the value your machine has.

**Comment by ntfshard** [comment] 2020-11-20 18:34
@lieser Thank you for your guidance. Sorry for delay. It seems I got the value, but not sure that I do it in the right way, could you please check:
![image](https://user-images.githubusercontent.com/4844306/99836935-de8fca00-2b77-11eb-953f-a941fd69123f.png)
W/o a call value was undefined. 0n3375 is a dec? I'm quite new with windbg (

**Comment by lieser** [comment] 2020-11-21 11:57
Also not an expert on WinDbg, but as far as I can tell you did everything right. But does this error still happen to you with the latest cronbuild?
We already updated `MAX_CONTEXT_64_SIZE` to `0xd2f` (decimal `3375`) in a PR. As this is the same value as you found out for your machine, I would expect the latest cronbuild to work for you.

**Comment by ntfshard** [comment] 2020-11-24 10:22
Ok, I see, thank you. The difficult is that drmemory crontab releases are appear quite rare: latest - 12 Sep, previous - 4 Jul and 4 Apr

**Comment by ntfshard** [comment] 2021-01-13 14:02
Hello
Thank you for fixing crontab releases. I ran 2.3.18633 and it works fine.

**Comment by derekbruening** [comment] 2021-01-31 17:37
I think this was accidentally closed: the hardcoded constant was raised, fixing it short-term, but this issue covers a long-term dynamic-sizing fix.  Re-opening.

**Comment by derekbruening** [comment] 2021-01-31 21:46
Looks like thread_set_self_mcontext is one place where a heap buffer cannot be freed (at least locally).  I think all the others can easily heap-allocate.

**Closed** 2021-02-01 05:19 UTC
Labels: Bug-Assert, OpSys-Windows
