### ISSUE TITLE
"sample.inscount.prof-pcs.cleancall" fails on ARM

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2162] opened 2017-01-31 11:45 UTC
"sample.inscount.prof-pcs.cleancall" fails on ARM, if enabled. Error and call chain:

Not implemented @/.../dynamorio/core/arch/instr_shared.c:3085
insert_meta_call_vargs
dr_insert_clean_call_ex_varg
dr_insert_clean_call

**Comment by fhahn** [comment] 2018-03-29 09:12
#2905 is a duplicate of this one, but I am closing off this issue, as #2905 has a PR attached already

**Closed by fhahn** 2018-03-29 09:12 UTC
Labels: OpSys-ARM, Status-Duplicate
