### ISSUE TITLE
CRASH when running python with tensorflow on encountering AVX512 instruction

### ISSUE THREAD

**Issue by varun729** [DynamoRIO/dynamorio#4734] opened 2021-02-15 22:18 UTC
DynamoRIO crashes when running python with tensorflow on a machine that supports AVX512 instruction set. DynamoRIO is attached without any client like `drrun -debug -loglevel 3 -full_decode -- python .....`.

The error is "Invalid Instruction". On first glance, the bug looks very similar to #4652 but in my case drdisas cannot decode the instruction.

On checking the logs, I see that the invalid instruction has bytes `62 a1 7c 48 51 ff`. This instruction is `vsqrtps %zmm23,%zmm23`.
The below log shows that three AVX512 instructions preceding this instructions were decoded correctly.

<pre>
```
  0x00007fc343dea0a6  4c 8b 7c 24 10       mov    0x10(%rsp)[8byte] -> %r15
  0x00007fc343dea0ab  48 8b 74 24 18       mov    0x18(%rsp)[8byte] -> %rsi
  0x00007fc343dea0b0  4c 8b 6c 24 38       mov    0x38(%rsp)[8byte] -> %r13
  0x00007fc343dea0b5  4d 31 d2             xor    %r10 %r10 -> %r10
  0x00007fc343dea0b8  4d 31 c0             xor    %r8 %r8 -> %r8
  0x00007fc343dea0bb  62 21 7c 48 10 4c 05 vmovups {%k0} 0x00(%rbp,%r8)[64byte] -> %zmm25
                      00
  0x00007fc343dea0c3  62 a1 7c 48 10 3c 07 vmovups {%k0} (%rdi,%r8)[64byte] -> %zmm23
  0x00007fc343dea0ca  62 81 44 40 58 fc    vaddps {%k0} %zmm23 %zmm28 -> %zmm23
SYSLOG_ERROR: Possible unsupported evex encoding.
SYSLOG_WARNING: Invalid opcode encountered
Error decoding 0x00007fc343dea0d0 == 0x62 0xa1 0x7c 0x48 0x51 0xff
decode: invalid instr at 0x00007fc343dea0d0
Error decoding 0x00007fc343dea0d0 == 0x62 0xa1 0x7c 0x48 0x51 0xff
decode: invalid instr at 0x00007fc343dea0d0
  0x00007fc343dea0d0  62 a1 7c 48 51 ff...??  <INVALID>
interp: invalid instr at 0x00007fc343dea0d0
end_pc = 0x00007fc343dea0d0

exit_branch_type=0x0 bb->exit_target=0x00007fc343dea0d0
exit_branch_type=0x0 target=0x00007fc343dea0d0 l->flags=0x9801
Fragment 445210, tag 0x00007fc343dea000, flags 0x1000630, shared, size 213:
```
</pre>

**Versions**
 - DynamoRIO version 8.0.18639, custom build  (commit eb57ba)
 - Latest build didn't help (I tried it first)
 - OS: 5.4.0-52-generic #57~18.04.1-Ubuntu
 - 64-bit application

**Additional context**
The problem is specific to AVX512. It looks like the instruction is not yet supported in DynamoRIO.

**Comment by khuey** [comment] 2021-02-15 22:26
This is #4550

**Comment by abhinav92003** [comment] 2021-02-16 17:15
Closing this issue as it's a duplicate of #4550.

**Closed by abhinav92003** 2021-02-16 17:15 UTC

**Comment by khuey** [comment] 2021-02-17 21:06
Please try this with a build including df18aa86c2d5b2c3eb0bb2d487a22b7c9dda0d01

**Comment by varun729** [comment] 2021-02-17 22:01
@khuey thanks! this build solves the problem.
