### ISSUE TITLE
Can not run chrome

### ISSUE THREAD

**Issue by ganyao114** [DynamoRIO/dynamorio#3515] opened 2019-04-08 06:45 UTC
can not run chrome on ubuntu 16.04:

./drrun /opt/google/chrome/chrome

pending for a long time, have no response

**Comment by ganyao114** [comment] 2019-04-08 06:53
X86_64 Parallels Desktop on macOS

**Comment by hgreving2304** [comment] 2019-04-08 14:48
I can reproduce, doesn't work for me either. I'm actually not sure if we support a highly memory intensive and complex app like chrome.

**Comment by hgreving2304** [comment] 2019-04-08 16:07
Ok, I was wrong. We fully support Chrome on Linux and other platforms with no constraints. We will investigate. Thanks for filing.

**Comment by derekbruening** [comment] 2019-04-08 16:12
Right, we have run Chome on Windows and Linux in the past.

As always, @ganyao114, please run a debug build as the first step whenever anything goes wrong.
If I do that, I see what is probably a relatively recent change to Chrome to use PID namespaces which DR has not been updated to support:

```
$ bin64/drrun -- /opt/google/chrome/chrome
<Starting application /opt/google/chrome/chrome (118809)>
<Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/bruening/dr/git/build_x64_dbg_tests/lib64/debug/libdynamorio.so' 0x00007f7bb3bee798
>
<(1+x) Handling our fault in a TRY at 0x00007f7bb3e371b5>
<spurious rep/repne prefix @0x00007f7bb39ade58 (f2 41 ff e3): >
<-- parent 118809 forked child 118818 -->
<Stopping application /opt/google/chrome/chrome (118818)>
<-- parent 0 forked child 1 -->
<Application /opt/google/chrome/chrome (118809).  Internal Error: DynamoRIO debug check failure: /home/bruening/dr/git/src/core/unix/os.c:7864 parent != 0
(Error occurred @15271 frags)
```

Looks like #3423 probably coming from #1746.  If you'd like to volunteer to help implement that we would appreciate the contribution.  I'm going to close this as a duplicate -- we can open a separate issue if there are any further problems after that is addressed.

**Closed by derekbruening** 2019-04-08 16:12 UTC
Labels: Bug-AppFail, OpSys-Linux, help wanted

**Comment by derekbruening** [comment] 2019-04-08 16:17
To clarify, duplicate of #1746 which was also chrome

**Comment by ganyao114** [comment] 2019-04-11 03:19
> Right, we have run Chome on Windows and Linux in the past.
> 
> As always, @ganyao114, please run a debug build as the first step whenever anything goes wrong.
> If I do that, I see what is probably a relatively recent change to Chrome to use PID namespaces which DR has not been updated to support:
> 
> ```
> $ bin64/drrun -- /opt/google/chrome/chrome
> <Starting application /opt/google/chrome/chrome (118809)>
> <Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
> <Paste into GDB to debug DynamoRIO clients:
> set confirm off
> add-symbol-file '/home/bruening/dr/git/build_x64_dbg_tests/lib64/debug/libdynamorio.so' 0x00007f7bb3bee798
> >
> <(1+x) Handling our fault in a TRY at 0x00007f7bb3e371b5>
> <spurious rep/repne prefix @0x00007f7bb39ade58 (f2 41 ff e3): >
> <-- parent 118809 forked child 118818 -->
> <Stopping application /opt/google/chrome/chrome (118818)>
> <-- parent 0 forked child 1 -->
> <Application /opt/google/chrome/chrome (118809).  Internal Error: DynamoRIO debug check failure: /home/bruening/dr/git/src/core/unix/os.c:7864 parent != 0
> (Error occurred @15271 frags)
> ```
> Looks like #3423 probably coming from #1746. If you'd like to volunteer to help implement that we would appreciate the contribution. I'm going to close this as a duplicate -- we can open a separate issue if there are any further problems after that is addressed.

Thanks
